/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptInvitationResponseDto,
  CreateInvitationDto,
  CreatedInvitationResponseDto,
  InvitationListResponseDto,
  InvitationPreviewResponseDto,
  InvitationTokenDto,
  InvitationsControllerListParams
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type invitationsControllerCreateResponse201 = {
  data: CreatedInvitationResponseDto
  status: 201
}

export type invitationsControllerCreateResponse403 = {
  data: void
  status: 403
}

export type invitationsControllerCreateResponse409 = {
  data: void
  status: 409
}

export type invitationsControllerCreateResponseSuccess = (invitationsControllerCreateResponse201) & {
  headers: Headers;
};
export type invitationsControllerCreateResponseError = (invitationsControllerCreateResponse403 | invitationsControllerCreateResponse409) & {
  headers: Headers;
};

export type invitationsControllerCreateResponse = (invitationsControllerCreateResponseSuccess | invitationsControllerCreateResponseError)

export const getInvitationsControllerCreateUrl = () => {




  return `/api/v1/invitations`
}

/**
 * @summary Aktif organizasyona davet; bağlantı mail ile gider.
 */
export const invitationsControllerCreate = async (createInvitationDto: CreateInvitationDto, options?: Parameters<typeof customFetch>[1]): Promise<invitationsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<invitationsControllerCreateResponse>(getInvitationsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createInvitationDto)
  }
);}





export const getInvitationsControllerCreateMutationKey = () => ['invitationsControllerCreate'] as const;

export const getInvitationsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerCreate>>, TError,InvitationsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerCreate>>, TError,InvitationsControllerCreateMutationVariables, TContext> => {

const mutationKey = getInvitationsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invitationsControllerCreate>>, InvitationsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  invitationsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InvitationsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerCreate>>>
    export type InvitationsControllerCreateMutationBody = CreateInvitationDto
    export type InvitationsControllerCreateMutationError = void
    export type InvitationsControllerCreateMutationVariables = {data: CreateInvitationDto}

    /**
 * @summary Aktif organizasyona davet; bağlantı mail ile gider.
 */
export const useInvitationsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerCreate>>, TError,InvitationsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invitationsControllerCreate>>,
        TError,
        InvitationsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getInvitationsControllerCreateMutationOptions(options), queryClient);
    }
    export type invitationsControllerListResponse200 = {
  data: InvitationListResponseDto
  status: 200
}

export type invitationsControllerListResponseSuccess = (invitationsControllerListResponse200) & {
  headers: Headers;
};
;

export type invitationsControllerListResponse = (invitationsControllerListResponseSuccess)

export const getInvitationsControllerListUrl = (params: InvitationsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/invitations?${stringifiedParams}` : `/api/v1/invitations`
}

/**
 * @summary Aktif organizasyonun kabul edilmemiş davetleri.
 */
export const invitationsControllerList = async (params: InvitationsControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<invitationsControllerListResponse> => {

  return customFetch<invitationsControllerListResponse>(getInvitationsControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getInvitationsControllerListQueryKey = (params?: InvitationsControllerListParams,) => {
    return [
    `/api/v1/invitations`, ...(params ? [params] : [])
    ] as const;
    }


export const getInvitationsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(params: InvitationsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvitationsControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof invitationsControllerList>>> = ({ signal }) => invitationsControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvitationsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerList>>>
export type InvitationsControllerListQueryError = unknown


export function useInvitationsControllerList<TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(
 params: InvitationsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof invitationsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvitationsControllerList<TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(
 params: InvitationsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof invitationsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvitationsControllerList<TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(
 params: InvitationsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Aktif organizasyonun kabul edilmemiş davetleri.
 */

export function useInvitationsControllerList<TData = Awaited<ReturnType<typeof invitationsControllerList>>, TError = unknown>(
 params: InvitationsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvitationsControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type invitationsControllerRevokeResponse204 = {
  data: void
  status: 204
}

export type invitationsControllerRevokeResponse404 = {
  data: void
  status: 404
}

export type invitationsControllerRevokeResponseSuccess = (invitationsControllerRevokeResponse204) & {
  headers: Headers;
};
export type invitationsControllerRevokeResponseError = (invitationsControllerRevokeResponse404) & {
  headers: Headers;
};

export type invitationsControllerRevokeResponse = (invitationsControllerRevokeResponseSuccess | invitationsControllerRevokeResponseError)

export const getInvitationsControllerRevokeUrl = (id: string,) => {




  return `/api/v1/invitations/${id}`
}

/**
 * @summary Bekleyen daveti geri çeker.
 */
export const invitationsControllerRevoke = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<invitationsControllerRevokeResponse> => {

  return customFetch<invitationsControllerRevokeResponse>(getInvitationsControllerRevokeUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getInvitationsControllerRevokeMutationKey = () => ['invitationsControllerRevoke'] as const;

export const getInvitationsControllerRevokeMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerRevoke>>, TError,InvitationsControllerRevokeMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerRevoke>>, TError,InvitationsControllerRevokeMutationVariables, TContext> => {

const mutationKey = getInvitationsControllerRevokeMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invitationsControllerRevoke>>, InvitationsControllerRevokeMutationVariables> = (props) => {
          const {id} = props ?? {};

          return  invitationsControllerRevoke(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InvitationsControllerRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerRevoke>>>

    export type InvitationsControllerRevokeMutationError = void
    export type InvitationsControllerRevokeMutationVariables = {id: string}

    /**
 * @summary Bekleyen daveti geri çeker.
 */
export const useInvitationsControllerRevoke = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerRevoke>>, TError,InvitationsControllerRevokeMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invitationsControllerRevoke>>,
        TError,
        InvitationsControllerRevokeMutationVariables,
        TContext
      > => {
      return useMutation(getInvitationsControllerRevokeMutationOptions(options), queryClient);
    }
    export type invitationsControllerPreviewResponse200 = {
  data: InvitationPreviewResponseDto
  status: 200
}

export type invitationsControllerPreviewResponse404 = {
  data: void
  status: 404
}

export type invitationsControllerPreviewResponse409 = {
  data: void
  status: 409
}

export type invitationsControllerPreviewResponse410 = {
  data: void
  status: 410
}

export type invitationsControllerPreviewResponseSuccess = (invitationsControllerPreviewResponse200) & {
  headers: Headers;
};
export type invitationsControllerPreviewResponseError = (invitationsControllerPreviewResponse404 | invitationsControllerPreviewResponse409 | invitationsControllerPreviewResponse410) & {
  headers: Headers;
};

export type invitationsControllerPreviewResponse = (invitationsControllerPreviewResponseSuccess | invitationsControllerPreviewResponseError)

export const getInvitationsControllerPreviewUrl = () => {




  return `/api/v1/invitations/preview`
}

/**
 * @summary Kabul ekranı için davetin özeti. Oturum gerekmez; token yetki belgesidir.
 */
export const invitationsControllerPreview = async (invitationTokenDto: InvitationTokenDto, options?: Parameters<typeof customFetch>[1]): Promise<invitationsControllerPreviewResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<invitationsControllerPreviewResponse>(getInvitationsControllerPreviewUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(invitationTokenDto)
  }
);}





export const getInvitationsControllerPreviewMutationKey = () => ['invitationsControllerPreview'] as const;

export const getInvitationsControllerPreviewMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerPreview>>, TError,InvitationsControllerPreviewMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerPreview>>, TError,InvitationsControllerPreviewMutationVariables, TContext> => {

const mutationKey = getInvitationsControllerPreviewMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invitationsControllerPreview>>, InvitationsControllerPreviewMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  invitationsControllerPreview(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InvitationsControllerPreviewMutationResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerPreview>>>
    export type InvitationsControllerPreviewMutationBody = InvitationTokenDto
    export type InvitationsControllerPreviewMutationError = void
    export type InvitationsControllerPreviewMutationVariables = {data: InvitationTokenDto}

    /**
 * @summary Kabul ekranı için davetin özeti. Oturum gerekmez; token yetki belgesidir.
 */
export const useInvitationsControllerPreview = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerPreview>>, TError,InvitationsControllerPreviewMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invitationsControllerPreview>>,
        TError,
        InvitationsControllerPreviewMutationVariables,
        TContext
      > => {
      return useMutation(getInvitationsControllerPreviewMutationOptions(options), queryClient);
    }
    export type invitationsControllerAcceptResponse200 = {
  data: AcceptInvitationResponseDto
  status: 200
}

export type invitationsControllerAcceptResponse403 = {
  data: void
  status: 403
}

export type invitationsControllerAcceptResponse404 = {
  data: void
  status: 404
}

export type invitationsControllerAcceptResponse409 = {
  data: void
  status: 409
}

export type invitationsControllerAcceptResponse410 = {
  data: void
  status: 410
}

export type invitationsControllerAcceptResponseSuccess = (invitationsControllerAcceptResponse200) & {
  headers: Headers;
};
export type invitationsControllerAcceptResponseError = (invitationsControllerAcceptResponse403 | invitationsControllerAcceptResponse404 | invitationsControllerAcceptResponse409 | invitationsControllerAcceptResponse410) & {
  headers: Headers;
};

export type invitationsControllerAcceptResponse = (invitationsControllerAcceptResponseSuccess | invitationsControllerAcceptResponseError)

export const getInvitationsControllerAcceptUrl = () => {




  return `/api/v1/invitations/accept`
}

/**
 * @summary Oturumdaki mevcut kullanıcı daveti kabul eder. Hesabı olmayanlar
`POST /auth/register-invited` ile kayıt olur.
 */
export const invitationsControllerAccept = async (invitationTokenDto: InvitationTokenDto, options?: Parameters<typeof customFetch>[1]): Promise<invitationsControllerAcceptResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<invitationsControllerAcceptResponse>(getInvitationsControllerAcceptUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(invitationTokenDto)
  }
);}





export const getInvitationsControllerAcceptMutationKey = () => ['invitationsControllerAccept'] as const;

export const getInvitationsControllerAcceptMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerAccept>>, TError,InvitationsControllerAcceptMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerAccept>>, TError,InvitationsControllerAcceptMutationVariables, TContext> => {

const mutationKey = getInvitationsControllerAcceptMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invitationsControllerAccept>>, InvitationsControllerAcceptMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  invitationsControllerAccept(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InvitationsControllerAcceptMutationResult = NonNullable<Awaited<ReturnType<typeof invitationsControllerAccept>>>
    export type InvitationsControllerAcceptMutationBody = InvitationTokenDto
    export type InvitationsControllerAcceptMutationError = void
    export type InvitationsControllerAcceptMutationVariables = {data: InvitationTokenDto}

    /**
 * @summary Oturumdaki mevcut kullanıcı daveti kabul eder. Hesabı olmayanlar
`POST /auth/register-invited` ile kayıt olur.
 */
export const useInvitationsControllerAccept = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitationsControllerAccept>>, TError,InvitationsControllerAcceptMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invitationsControllerAccept>>,
        TError,
        InvitationsControllerAcceptMutationVariables,
        TContext
      > => {
      return useMutation(getInvitationsControllerAcceptMutationOptions(options), queryClient);
    }
