/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOrganizationDto,
  OrganizationResponseDto,
  OrganizationsControllerListParams,
  UpdateOrganizationDto,
  UserOrganizationListResponseDto,
  UserOrganizationResponseDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type organizationsControllerCreateResponse201 = {
  data: UserOrganizationResponseDto
  status: 201
}

export type organizationsControllerCreateResponse409 = {
  data: void
  status: 409
}

export type organizationsControllerCreateResponseSuccess = (organizationsControllerCreateResponse201) & {
  headers: Headers;
};
export type organizationsControllerCreateResponseError = (organizationsControllerCreateResponse409) & {
  headers: Headers;
};

export type organizationsControllerCreateResponse = (organizationsControllerCreateResponseSuccess | organizationsControllerCreateResponseError)

export const getOrganizationsControllerCreateUrl = () => {




  return `/api/v1/organizations`
}

/**
 * @summary Yeni organizasyon; oluşturan kullanıcı owner olur.
 */
export const organizationsControllerCreate = async (createOrganizationDto: CreateOrganizationDto, options?: Parameters<typeof customFetch>[1]): Promise<organizationsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<organizationsControllerCreateResponse>(getOrganizationsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createOrganizationDto)
  }
);}





export const getOrganizationsControllerCreateMutationKey = () => ['organizationsControllerCreate'] as const;

export const getOrganizationsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerCreate>>, TError,OrganizationsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerCreate>>, TError,OrganizationsControllerCreateMutationVariables, TContext> => {

const mutationKey = getOrganizationsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsControllerCreate>>, OrganizationsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  organizationsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerCreate>>>
    export type OrganizationsControllerCreateMutationBody = CreateOrganizationDto
    export type OrganizationsControllerCreateMutationError = void
    export type OrganizationsControllerCreateMutationVariables = {data: CreateOrganizationDto}

    /**
 * @summary Yeni organizasyon; oluşturan kullanıcı owner olur.
 */
export const useOrganizationsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerCreate>>, TError,OrganizationsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsControllerCreate>>,
        TError,
        OrganizationsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getOrganizationsControllerCreateMutationOptions(options), queryClient);
    }
    export type organizationsControllerListResponse200 = {
  data: UserOrganizationListResponseDto
  status: 200
}

export type organizationsControllerListResponseSuccess = (organizationsControllerListResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerListResponse = (organizationsControllerListResponseSuccess)

export const getOrganizationsControllerListUrl = (params: OrganizationsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations?${stringifiedParams}` : `/api/v1/organizations`
}

/**
 * @summary Kullanıcının üye olduğu organizasyonlar. X-Org-Id gerekmez.
 */
export const organizationsControllerList = async (params: OrganizationsControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<organizationsControllerListResponse> => {

  return customFetch<organizationsControllerListResponse>(getOrganizationsControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getOrganizationsControllerListQueryKey = (params?: OrganizationsControllerListParams,) => {
    return [
    `/api/v1/organizations`, ...(params ? [params] : [])
    ] as const;
    }


export const getOrganizationsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof organizationsControllerList>>, TError = unknown>(params: OrganizationsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsControllerList>>> = ({ signal }) => organizationsControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerList>>>
export type OrganizationsControllerListQueryError = unknown


export function useOrganizationsControllerList<TData = Awaited<ReturnType<typeof organizationsControllerList>>, TError = unknown>(
 params: OrganizationsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsControllerList<TData = Awaited<ReturnType<typeof organizationsControllerList>>, TError = unknown>(
 params: OrganizationsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsControllerList<TData = Awaited<ReturnType<typeof organizationsControllerList>>, TError = unknown>(
 params: OrganizationsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Kullanıcının üye olduğu organizasyonlar. X-Org-Id gerekmez.
 */

export function useOrganizationsControllerList<TData = Awaited<ReturnType<typeof organizationsControllerList>>, TError = unknown>(
 params: OrganizationsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type organizationsControllerGetCurrentResponse200 = {
  data: OrganizationResponseDto
  status: 200
}

export type organizationsControllerGetCurrentResponseSuccess = (organizationsControllerGetCurrentResponse200) & {
  headers: Headers;
};
;

export type organizationsControllerGetCurrentResponse = (organizationsControllerGetCurrentResponseSuccess)

export const getOrganizationsControllerGetCurrentUrl = () => {




  return `/api/v1/organizations/current`
}

/**
 * @summary X-Org-Id ile seçilen organizasyon.
 */
export const organizationsControllerGetCurrent = async ( options?: Parameters<typeof customFetch>[1]): Promise<organizationsControllerGetCurrentResponse> => {

  return customFetch<organizationsControllerGetCurrentResponse>(getOrganizationsControllerGetCurrentUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getOrganizationsControllerGetCurrentQueryKey = () => {
    return [
    `/api/v1/organizations/current`
    ] as const;
    }


export const getOrganizationsControllerGetCurrentQueryOptions = <TData = Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsControllerGetCurrentQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsControllerGetCurrent>>> = ({ signal }) => organizationsControllerGetCurrent({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsControllerGetCurrentQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerGetCurrent>>>
export type OrganizationsControllerGetCurrentQueryError = unknown


export function useOrganizationsControllerGetCurrent<TData = Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetCurrent>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsControllerGetCurrent<TData = Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsControllerGetCurrent>>,
          TError,
          Awaited<ReturnType<typeof organizationsControllerGetCurrent>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsControllerGetCurrent<TData = Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary X-Org-Id ile seçilen organizasyon.
 */

export function useOrganizationsControllerGetCurrent<TData = Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsControllerGetCurrent>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsControllerGetCurrentQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type organizationsControllerUpdateResponse200 = {
  data: OrganizationResponseDto
  status: 200
}

export type organizationsControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type organizationsControllerUpdateResponse409 = {
  data: void
  status: 409
}

export type organizationsControllerUpdateResponseSuccess = (organizationsControllerUpdateResponse200) & {
  headers: Headers;
};
export type organizationsControllerUpdateResponseError = (organizationsControllerUpdateResponse403 | organizationsControllerUpdateResponse409) & {
  headers: Headers;
};

export type organizationsControllerUpdateResponse = (organizationsControllerUpdateResponseSuccess | organizationsControllerUpdateResponseError)

export const getOrganizationsControllerUpdateUrl = () => {




  return `/api/v1/organizations/current`
}

export const organizationsControllerUpdate = async (updateOrganizationDto: UpdateOrganizationDto, options?: Parameters<typeof customFetch>[1]): Promise<organizationsControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<organizationsControllerUpdateResponse>(getOrganizationsControllerUpdateUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateOrganizationDto)
  }
);}





export const getOrganizationsControllerUpdateMutationKey = () => ['organizationsControllerUpdate'] as const;

export const getOrganizationsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerUpdate>>, TError,OrganizationsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerUpdate>>, TError,OrganizationsControllerUpdateMutationVariables, TContext> => {

const mutationKey = getOrganizationsControllerUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsControllerUpdate>>, OrganizationsControllerUpdateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  organizationsControllerUpdate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerUpdate>>>
    export type OrganizationsControllerUpdateMutationBody = UpdateOrganizationDto
    export type OrganizationsControllerUpdateMutationError = void
    export type OrganizationsControllerUpdateMutationVariables = {data: UpdateOrganizationDto}

    export const useOrganizationsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerUpdate>>, TError,OrganizationsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsControllerUpdate>>,
        TError,
        OrganizationsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getOrganizationsControllerUpdateMutationOptions(options), queryClient);
    }
    export type organizationsControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type organizationsControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type organizationsControllerDeleteResponseSuccess = (organizationsControllerDeleteResponse204) & {
  headers: Headers;
};
export type organizationsControllerDeleteResponseError = (organizationsControllerDeleteResponse403) & {
  headers: Headers;
};

export type organizationsControllerDeleteResponse = (organizationsControllerDeleteResponseSuccess | organizationsControllerDeleteResponseError)

export const getOrganizationsControllerDeleteUrl = () => {




  return `/api/v1/organizations/current`
}

/**
 * @summary Organizasyonu, üyeliklerini ve davetlerini siler.
 */
export const organizationsControllerDelete = async ( options?: Parameters<typeof customFetch>[1]): Promise<organizationsControllerDeleteResponse> => {

  return customFetch<organizationsControllerDeleteResponse>(getOrganizationsControllerDeleteUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getOrganizationsControllerDeleteMutationKey = () => ['organizationsControllerDelete'] as const;

export const getOrganizationsControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerDelete>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerDelete>>, TError,void, TContext> => {

const mutationKey = getOrganizationsControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsControllerDelete>>, void> = () => {


          return  organizationsControllerDelete(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsControllerDelete>>>

    export type OrganizationsControllerDeleteMutationError = void


    /**
 * @summary Organizasyonu, üyeliklerini ve davetlerini siler.
 */
export const useOrganizationsControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsControllerDelete>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsControllerDelete>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getOrganizationsControllerDeleteMutationOptions(options), queryClient);
    }
