/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateProjectDto,
  ProjectListResponseDto,
  ProjectResponseDto,
  ProjectsControllerListParams,
  UpdateProjectDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type projectsControllerListResponse200 = {
  data: ProjectListResponseDto
  status: 200
}

export type projectsControllerListResponse403 = {
  data: void
  status: 403
}

export type projectsControllerListResponseSuccess = (projectsControllerListResponse200) & {
  headers: Headers;
};
export type projectsControllerListResponseError = (projectsControllerListResponse403) & {
  headers: Headers;
};

export type projectsControllerListResponse = (projectsControllerListResponseSuccess | projectsControllerListResponseError)

export const getProjectsControllerListUrl = (params: ProjectsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects?${stringifiedParams}` : `/api/v1/projects`
}

/**
 * @summary `client_viewer` yalnız kendi client'ının projelerini görür.
 */
export const projectsControllerList = async (params: ProjectsControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<projectsControllerListResponse> => {

  return customFetch<projectsControllerListResponse>(getProjectsControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProjectsControllerListQueryKey = (params?: ProjectsControllerListParams,) => {
    return [
    `/api/v1/projects`, ...(params ? [params] : [])
    ] as const;
    }


export const getProjectsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerList>>, TError = void>(params: ProjectsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerList>>> = ({ signal }) => projectsControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerList>>>
export type ProjectsControllerListQueryError = void


export function useProjectsControllerList<TData = Awaited<ReturnType<typeof projectsControllerList>>, TError = void>(
 params: ProjectsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerList>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerList<TData = Awaited<ReturnType<typeof projectsControllerList>>, TError = void>(
 params: ProjectsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerList>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerList<TData = Awaited<ReturnType<typeof projectsControllerList>>, TError = void>(
 params: ProjectsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary `client_viewer` yalnız kendi client'ının projelerini görür.
 */

export function useProjectsControllerList<TData = Awaited<ReturnType<typeof projectsControllerList>>, TError = void>(
 params: ProjectsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type projectsControllerCreateResponse201 = {
  data: ProjectResponseDto
  status: 201
}

export type projectsControllerCreateResponse403 = {
  data: void
  status: 403
}

export type projectsControllerCreateResponse409 = {
  data: void
  status: 409
}

export type projectsControllerCreateResponseSuccess = (projectsControllerCreateResponse201) & {
  headers: Headers;
};
export type projectsControllerCreateResponseError = (projectsControllerCreateResponse403 | projectsControllerCreateResponse409) & {
  headers: Headers;
};

export type projectsControllerCreateResponse = (projectsControllerCreateResponseSuccess | projectsControllerCreateResponseError)

export const getProjectsControllerCreateUrl = () => {




  return `/api/v1/projects`
}

export const projectsControllerCreate = async (createProjectDto: CreateProjectDto, options?: Parameters<typeof customFetch>[1]): Promise<projectsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<projectsControllerCreateResponse>(getProjectsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createProjectDto)
  }
);}





export const getProjectsControllerCreateMutationKey = () => ['projectsControllerCreate'] as const;

export const getProjectsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError,ProjectsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError,ProjectsControllerCreateMutationVariables, TContext> => {

const mutationKey = getProjectsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerCreate>>, ProjectsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  projectsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerCreate>>>
    export type ProjectsControllerCreateMutationBody = CreateProjectDto
    export type ProjectsControllerCreateMutationError = void
    export type ProjectsControllerCreateMutationVariables = {data: CreateProjectDto}

    export const useProjectsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerCreate>>, TError,ProjectsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerCreate>>,
        TError,
        ProjectsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getProjectsControllerCreateMutationOptions(options), queryClient);
    }
    export type projectsControllerFindOneResponse200 = {
  data: ProjectResponseDto
  status: 200
}

export type projectsControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type projectsControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type projectsControllerFindOneResponseSuccess = (projectsControllerFindOneResponse200) & {
  headers: Headers;
};
export type projectsControllerFindOneResponseError = (projectsControllerFindOneResponse403 | projectsControllerFindOneResponse404) & {
  headers: Headers;
};

export type projectsControllerFindOneResponse = (projectsControllerFindOneResponseSuccess | projectsControllerFindOneResponseError)

export const getProjectsControllerFindOneUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}`
}

export const projectsControllerFindOne = async (projectId: string, options?: Parameters<typeof customFetch>[1]): Promise<projectsControllerFindOneResponse> => {

  return customFetch<projectsControllerFindOneResponse>(getProjectsControllerFindOneUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getProjectsControllerFindOneQueryKey = (projectId: string,) => {
    return [
    `/api/v1/projects/${projectId}`
    ] as const;
    }


export const getProjectsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof projectsControllerFindOne>>, TError = void>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getProjectsControllerFindOneQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof projectsControllerFindOne>>> = ({ signal }) => projectsControllerFindOne(projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ProjectsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof projectsControllerFindOne>>>
export type ProjectsControllerFindOneQueryError = void


export function useProjectsControllerFindOne<TData = Awaited<ReturnType<typeof projectsControllerFindOne>>, TError = void>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerFindOne<TData = Awaited<ReturnType<typeof projectsControllerFindOne>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof projectsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof projectsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useProjectsControllerFindOne<TData = Awaited<ReturnType<typeof projectsControllerFindOne>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useProjectsControllerFindOne<TData = Awaited<ReturnType<typeof projectsControllerFindOne>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof projectsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getProjectsControllerFindOneQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type projectsControllerUpdateResponse200 = {
  data: ProjectResponseDto
  status: 200
}

export type projectsControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type projectsControllerUpdateResponse404 = {
  data: void
  status: 404
}

export type projectsControllerUpdateResponse409 = {
  data: void
  status: 409
}

export type projectsControllerUpdateResponseSuccess = (projectsControllerUpdateResponse200) & {
  headers: Headers;
};
export type projectsControllerUpdateResponseError = (projectsControllerUpdateResponse403 | projectsControllerUpdateResponse404 | projectsControllerUpdateResponse409) & {
  headers: Headers;
};

export type projectsControllerUpdateResponse = (projectsControllerUpdateResponseSuccess | projectsControllerUpdateResponseError)

export const getProjectsControllerUpdateUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}`
}

export const projectsControllerUpdate = async (projectId: string,
    updateProjectDto: UpdateProjectDto, options?: Parameters<typeof customFetch>[1]): Promise<projectsControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<projectsControllerUpdateResponse>(getProjectsControllerUpdateUrl(projectId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateProjectDto)
  }
);}





export const getProjectsControllerUpdateMutationKey = () => ['projectsControllerUpdate'] as const;

export const getProjectsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError,ProjectsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError,ProjectsControllerUpdateMutationVariables, TContext> => {

const mutationKey = getProjectsControllerUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerUpdate>>, ProjectsControllerUpdateMutationVariables> = (props) => {
          const {projectId,data} = props ?? {};

          return  projectsControllerUpdate(projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerUpdate>>>
    export type ProjectsControllerUpdateMutationBody = UpdateProjectDto
    export type ProjectsControllerUpdateMutationError = void
    export type ProjectsControllerUpdateMutationVariables = {projectId: string;data: UpdateProjectDto}

    export const useProjectsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerUpdate>>, TError,ProjectsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerUpdate>>,
        TError,
        ProjectsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getProjectsControllerUpdateMutationOptions(options), queryClient);
    }
    export type projectsControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type projectsControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type projectsControllerDeleteResponse404 = {
  data: void
  status: 404
}

export type projectsControllerDeleteResponseSuccess = (projectsControllerDeleteResponse204) & {
  headers: Headers;
};
export type projectsControllerDeleteResponseError = (projectsControllerDeleteResponse403 | projectsControllerDeleteResponse404) & {
  headers: Headers;
};

export type projectsControllerDeleteResponse = (projectsControllerDeleteResponseSuccess | projectsControllerDeleteResponseError)

export const getProjectsControllerDeleteUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}`
}

export const projectsControllerDelete = async (projectId: string, options?: Parameters<typeof customFetch>[1]): Promise<projectsControllerDeleteResponse> => {

  return customFetch<projectsControllerDeleteResponse>(getProjectsControllerDeleteUrl(projectId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getProjectsControllerDeleteMutationKey = () => ['projectsControllerDelete'] as const;

export const getProjectsControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerDelete>>, TError,ProjectsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof projectsControllerDelete>>, TError,ProjectsControllerDeleteMutationVariables, TContext> => {

const mutationKey = getProjectsControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof projectsControllerDelete>>, ProjectsControllerDeleteMutationVariables> = (props) => {
          const {projectId} = props ?? {};

          return  projectsControllerDelete(projectId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProjectsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof projectsControllerDelete>>>

    export type ProjectsControllerDeleteMutationError = void
    export type ProjectsControllerDeleteMutationVariables = {projectId: string}

    export const useProjectsControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof projectsControllerDelete>>, TError,ProjectsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof projectsControllerDelete>>,
        TError,
        ProjectsControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getProjectsControllerDeleteMutationOptions(options), queryClient);
    }
