/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  UsageControllerReportParams,
  UsageReportResponseDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type usageControllerReportResponse200 = {
  data: UsageReportResponseDto
  status: 200
}

export type usageControllerReportResponse400 = {
  data: void
  status: 400
}

export type usageControllerReportResponse403 = {
  data: void
  status: 403
}

export type usageControllerReportResponseSuccess = (usageControllerReportResponse200) & {
  headers: Headers;
};
export type usageControllerReportResponseError = (usageControllerReportResponse400 | usageControllerReportResponse403) & {
  headers: Headers;
};

export type usageControllerReportResponse = (usageControllerReportResponseSuccess | usageControllerReportResponseError)

export const getUsageControllerReportUrl = (params?: UsageControllerReportParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/usage?${stringifiedParams}` : `/api/v1/usage`
}

export const usageControllerReport = async (params?: UsageControllerReportParams, options?: Parameters<typeof customFetch>[1]): Promise<usageControllerReportResponse> => {

  return customFetch<usageControllerReportResponse>(getUsageControllerReportUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUsageControllerReportQueryKey = (params?: UsageControllerReportParams,) => {
    return [
    `/api/v1/usage`, ...(params ? [params] : [])
    ] as const;
    }


export const getUsageControllerReportQueryOptions = <TData = Awaited<ReturnType<typeof usageControllerReport>>, TError = void>(params?: UsageControllerReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usageControllerReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsageControllerReportQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof usageControllerReport>>> = ({ signal }) => usageControllerReport(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usageControllerReport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsageControllerReportQueryResult = NonNullable<Awaited<ReturnType<typeof usageControllerReport>>>
export type UsageControllerReportQueryError = void


export function useUsageControllerReport<TData = Awaited<ReturnType<typeof usageControllerReport>>, TError = void>(
 params: undefined |  UsageControllerReportParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usageControllerReport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usageControllerReport>>,
          TError,
          Awaited<ReturnType<typeof usageControllerReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsageControllerReport<TData = Awaited<ReturnType<typeof usageControllerReport>>, TError = void>(
 params?: UsageControllerReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usageControllerReport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usageControllerReport>>,
          TError,
          Awaited<ReturnType<typeof usageControllerReport>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsageControllerReport<TData = Awaited<ReturnType<typeof usageControllerReport>>, TError = void>(
 params?: UsageControllerReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usageControllerReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsageControllerReport<TData = Awaited<ReturnType<typeof usageControllerReport>>, TError = void>(
 params?: UsageControllerReportParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usageControllerReport>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsageControllerReportQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






