/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as OrganizationsNewRouteImport } from './routes/organizations.new'
import { Route as AppClientsIndexRouteImport } from './routes/_app/clients/index'
import { Route as AppClientsClientIdRouteImport } from './routes/_app/clients/$clientId'
import { Route as AppClientsNewRouteImport } from './routes/_app/clients/new'
import { Route as AppMembersIndexRouteImport } from './routes/_app/members/index'
import { Route as AppNotificationsIndexRouteImport } from './routes/_app/notifications/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppProjectsNewRouteImport } from './routes/_app/projects/new'
import { Route as PrintReportsReportIdRouteImport } from './routes/print.reports.$reportId'
import { Route as AppProjectsProjectIdAlertsRouteImport } from './routes/_app/projects/$projectId_.alerts'
import { Route as AppProjectsProjectIdConnectionsRouteImport } from './routes/_app/projects/$projectId_.connections'
import { Route as AppProjectsProjectIdDashboardRouteImport } from './routes/_app/projects/$projectId_.dashboard'
import { Route as AppProjectsProjectIdExplorerRouteImport } from './routes/_app/projects/$projectId_.explorer'
import { Route as AppProjectsProjectIdKeywordsRouteImport } from './routes/_app/projects/$projectId_.keywords'
import { Route as AppProjectsProjectIdReportsRouteImport } from './routes/_app/projects/$projectId_.reports'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const OrganizationsNewRoute = OrganizationsNewRouteImport.update({
  id: '/organizations/new',
  path: '/organizations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppClientsIndexRoute = AppClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsClientIdRoute = AppClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsNewRoute = AppClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsIndexRoute = AppNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsNewRoute = AppProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AppRoute,
} as any)
const PrintReportsReportIdRoute = PrintReportsReportIdRouteImport.update({
  id: '/print/reports/$reportId',
  path: '/print/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProjectsProjectIdAlertsRoute =
  AppProjectsProjectIdAlertsRouteImport.update({
    id: '/projects/$projectId_/alerts',
    path: '/projects/$projectId/alerts',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdConnectionsRoute =
  AppProjectsProjectIdConnectionsRouteImport.update({
    id: '/projects/$projectId_/connections',
    path: '/projects/$projectId/connections',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdDashboardRoute =
  AppProjectsProjectIdDashboardRouteImport.update({
    id: '/projects/$projectId_/dashboard',
    path: '/projects/$projectId/dashboard',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdExplorerRoute =
  AppProjectsProjectIdExplorerRouteImport.update({
    id: '/projects/$projectId_/explorer',
    path: '/projects/$projectId/explorer',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdKeywordsRoute =
  AppProjectsProjectIdKeywordsRouteImport.update({
    id: '/projects/$projectId_/keywords',
    path: '/projects/$projectId/keywords',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdReportsRoute =
  AppProjectsProjectIdReportsRouteImport.update({
    id: '/projects/$projectId_/reports',
    path: '/projects/$projectId/reports',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/system': typeof AppSystemRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/print/reports/$reportId': typeof PrintReportsReportIdRoute
  '/clients/': typeof AppClientsIndexRoute
  '/members/': typeof AppMembersIndexRoute
  '/notifications/': typeof AppNotificationsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$projectId/alerts': typeof AppProjectsProjectIdAlertsRoute
  '/projects/$projectId/connections': typeof AppProjectsProjectIdConnectionsRoute
  '/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/projects/$projectId/explorer': typeof AppProjectsProjectIdExplorerRoute
  '/projects/$projectId/keywords': typeof AppProjectsProjectIdKeywordsRoute
  '/projects/$projectId/reports': typeof AppProjectsProjectIdReportsRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/system': typeof AppSystemRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/': typeof AppIndexRoute
  '/clients/$clientId': typeof AppClientsClientIdRoute
  '/clients/new': typeof AppClientsNewRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/projects/new': typeof AppProjectsNewRoute
  '/print/reports/$reportId': typeof PrintReportsReportIdRoute
  '/clients': typeof AppClientsIndexRoute
  '/members': typeof AppMembersIndexRoute
  '/notifications': typeof AppNotificationsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$projectId/alerts': typeof AppProjectsProjectIdAlertsRoute
  '/projects/$projectId/connections': typeof AppProjectsProjectIdConnectionsRoute
  '/projects/$projectId/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/projects/$projectId/explorer': typeof AppProjectsProjectIdExplorerRoute
  '/projects/$projectId/keywords': typeof AppProjectsProjectIdKeywordsRoute
  '/projects/$projectId/reports': typeof AppProjectsProjectIdReportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_app/system': typeof AppSystemRoute
  '/organizations/new': typeof OrganizationsNewRoute
  '/_app/': typeof AppIndexRoute
  '/_app/clients/$clientId': typeof AppClientsClientIdRoute
  '/_app/clients/new': typeof AppClientsNewRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/projects/new': typeof AppProjectsNewRoute
  '/print/reports/$reportId': typeof PrintReportsReportIdRoute
  '/_app/clients/': typeof AppClientsIndexRoute
  '/_app/members/': typeof AppMembersIndexRoute
  '/_app/notifications/': typeof AppNotificationsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$projectId_/alerts': typeof AppProjectsProjectIdAlertsRoute
  '/_app/projects/$projectId_/connections': typeof AppProjectsProjectIdConnectionsRoute
  '/_app/projects/$projectId_/dashboard': typeof AppProjectsProjectIdDashboardRoute
  '/_app/projects/$projectId_/explorer': typeof AppProjectsProjectIdExplorerRoute
  '/_app/projects/$projectId_/keywords': typeof AppProjectsProjectIdKeywordsRoute
  '/_app/projects/$projectId_/reports': typeof AppProjectsProjectIdReportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/system'
    | '/organizations/new'
    | '/clients/$clientId'
    | '/clients/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/print/reports/$reportId'
    | '/clients/'
    | '/members/'
    | '/notifications/'
    | '/projects/'
    | '/projects/$projectId/alerts'
    | '/projects/$projectId/connections'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/explorer'
    | '/projects/$projectId/keywords'
    | '/projects/$projectId/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/system'
    | '/organizations/new'
    | '/'
    | '/clients/$clientId'
    | '/clients/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/print/reports/$reportId'
    | '/clients'
    | '/members'
    | '/notifications'
    | '/projects'
    | '/projects/$projectId/alerts'
    | '/projects/$projectId/connections'
    | '/projects/$projectId/dashboard'
    | '/projects/$projectId/explorer'
    | '/projects/$projectId/keywords'
    | '/projects/$projectId/reports'
  id:
    | '__root__'
    | '/_app'
    | '/accept-invite'
    | '/login'
    | '/_app/system'
    | '/organizations/new'
    | '/_app/'
    | '/_app/clients/$clientId'
    | '/_app/clients/new'
    | '/_app/projects/$projectId'
    | '/_app/projects/new'
    | '/print/reports/$reportId'
    | '/_app/clients/'
    | '/_app/members/'
    | '/_app/notifications/'
    | '/_app/projects/'
    | '/_app/projects/$projectId_/alerts'
    | '/_app/projects/$projectId_/connections'
    | '/_app/projects/$projectId_/dashboard'
    | '/_app/projects/$projectId_/explorer'
    | '/_app/projects/$projectId_/keywords'
    | '/_app/projects/$projectId_/reports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  OrganizationsNewRoute: typeof OrganizationsNewRoute
  PrintReportsReportIdRoute: typeof PrintReportsReportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/organizations/new': {
      id: '/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof OrganizationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clients/': {
      id: '/_app/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AppClientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/$clientId': {
      id: '/_app/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AppClientsClientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients/new': {
      id: '/_app/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AppClientsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/': {
      id: '/_app/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications/': {
      id: '/_app/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AppNotificationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/new': {
      id: '/_app/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AppProjectsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/print/reports/$reportId': {
      id: '/print/reports/$reportId'
      path: '/print/reports/$reportId'
      fullPath: '/print/reports/$reportId'
      preLoaderRoute: typeof PrintReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/projects/$projectId_/alerts': {
      id: '/_app/projects/$projectId_/alerts'
      path: '/projects/$projectId/alerts'
      fullPath: '/projects/$projectId/alerts'
      preLoaderRoute: typeof AppProjectsProjectIdAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/connections': {
      id: '/_app/projects/$projectId_/connections'
      path: '/projects/$projectId/connections'
      fullPath: '/projects/$projectId/connections'
      preLoaderRoute: typeof AppProjectsProjectIdConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/dashboard': {
      id: '/_app/projects/$projectId_/dashboard'
      path: '/projects/$projectId/dashboard'
      fullPath: '/projects/$projectId/dashboard'
      preLoaderRoute: typeof AppProjectsProjectIdDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/explorer': {
      id: '/_app/projects/$projectId_/explorer'
      path: '/projects/$projectId/explorer'
      fullPath: '/projects/$projectId/explorer'
      preLoaderRoute: typeof AppProjectsProjectIdExplorerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/keywords': {
      id: '/_app/projects/$projectId_/keywords'
      path: '/projects/$projectId/keywords'
      fullPath: '/projects/$projectId/keywords'
      preLoaderRoute: typeof AppProjectsProjectIdKeywordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/reports': {
      id: '/_app/projects/$projectId_/reports'
      path: '/projects/$projectId/reports'
      fullPath: '/projects/$projectId/reports'
      preLoaderRoute: typeof AppProjectsProjectIdReportsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSystemRoute: typeof AppSystemRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClientsClientIdRoute: typeof AppClientsClientIdRoute
  AppClientsNewRoute: typeof AppClientsNewRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsNewRoute: typeof AppProjectsNewRoute
  AppClientsIndexRoute: typeof AppClientsIndexRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppNotificationsIndexRoute: typeof AppNotificationsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdAlertsRoute: typeof AppProjectsProjectIdAlertsRoute
  AppProjectsProjectIdConnectionsRoute: typeof AppProjectsProjectIdConnectionsRoute
  AppProjectsProjectIdDashboardRoute: typeof AppProjectsProjectIdDashboardRoute
  AppProjectsProjectIdExplorerRoute: typeof AppProjectsProjectIdExplorerRoute
  AppProjectsProjectIdKeywordsRoute: typeof AppProjectsProjectIdKeywordsRoute
  AppProjectsProjectIdReportsRoute: typeof AppProjectsProjectIdReportsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSystemRoute: AppSystemRoute,
  AppIndexRoute: AppIndexRoute,
  AppClientsClientIdRoute: AppClientsClientIdRoute,
  AppClientsNewRoute: AppClientsNewRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsNewRoute: AppProjectsNewRoute,
  AppClientsIndexRoute: AppClientsIndexRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppNotificationsIndexRoute: AppNotificationsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdAlertsRoute: AppProjectsProjectIdAlertsRoute,
  AppProjectsProjectIdConnectionsRoute: AppProjectsProjectIdConnectionsRoute,
  AppProjectsProjectIdDashboardRoute: AppProjectsProjectIdDashboardRoute,
  AppProjectsProjectIdExplorerRoute: AppProjectsProjectIdExplorerRoute,
  AppProjectsProjectIdKeywordsRoute: AppProjectsProjectIdKeywordsRoute,
  AppProjectsProjectIdReportsRoute: AppProjectsProjectIdReportsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  OrganizationsNewRoute: OrganizationsNewRoute,
  PrintReportsReportIdRoute: PrintReportsReportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
