/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  LocationReferenceListResponseDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type locationsControllerListResponse200 = {
  data: LocationReferenceListResponseDto
  status: 200
}

export type locationsControllerListResponseSuccess = (locationsControllerListResponse200) & {
  headers: Headers;
};
;

export type locationsControllerListResponse = (locationsControllerListResponseSuccess)

export const getLocationsControllerListUrl = () => {




  return `/api/v1/locations`
}

export const locationsControllerList = async ( options?: Parameters<typeof customFetch>[1]): Promise<locationsControllerListResponse> => {

  return customFetch<locationsControllerListResponse>(getLocationsControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getLocationsControllerListQueryKey = () => {
    return [
    `/api/v1/locations`
    ] as const;
    }


export const getLocationsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof locationsControllerList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLocationsControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof locationsControllerList>>> = ({ signal }) => locationsControllerList({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof locationsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LocationsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof locationsControllerList>>>
export type LocationsControllerListQueryError = unknown


export function useLocationsControllerList<TData = Awaited<ReturnType<typeof locationsControllerList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof locationsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocationsControllerList<TData = Awaited<ReturnType<typeof locationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof locationsControllerList>>,
          TError,
          Awaited<ReturnType<typeof locationsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLocationsControllerList<TData = Awaited<ReturnType<typeof locationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLocationsControllerList<TData = Awaited<ReturnType<typeof locationsControllerList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof locationsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLocationsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






