/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BulkAddKeywordsDto,
  BulkAddKeywordsResponseDto,
  CreateKeywordGroupDto,
  CreateTrackedKeywordDto,
  KeywordGroupListResponseDto,
  KeywordGroupResponseDto,
  KeywordGroupsControllerListParams,
  KeywordSuggestionsResponseDto,
  TrackedKeywordListResponseDto,
  TrackedKeywordResponseDto,
  TrackedKeywordsControllerListParams,
  TrackedKeywordsControllerSuggestionsParams,
  UpdateKeywordGroupDto,
  UpdateTrackedKeywordDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type keywordGroupsControllerListResponse200 = {
  data: KeywordGroupListResponseDto
  status: 200
}

export type keywordGroupsControllerListResponse403 = {
  data: void
  status: 403
}

export type keywordGroupsControllerListResponse404 = {
  data: void
  status: 404
}

export type keywordGroupsControllerListResponseSuccess = (keywordGroupsControllerListResponse200) & {
  headers: Headers;
};
export type keywordGroupsControllerListResponseError = (keywordGroupsControllerListResponse403 | keywordGroupsControllerListResponse404) & {
  headers: Headers;
};

export type keywordGroupsControllerListResponse = (keywordGroupsControllerListResponseSuccess | keywordGroupsControllerListResponseError)

export const getKeywordGroupsControllerListUrl = (projectId: string,
    params: KeywordGroupsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/keyword-groups?${stringifiedParams}` : `/api/v1/projects/${projectId}/keyword-groups`
}

export const keywordGroupsControllerList = async (projectId: string,
    params: KeywordGroupsControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<keywordGroupsControllerListResponse> => {

  return customFetch<keywordGroupsControllerListResponse>(getKeywordGroupsControllerListUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getKeywordGroupsControllerListQueryKey = (projectId: string,
    params?: KeywordGroupsControllerListParams,) => {
    return [
    `/api/v1/projects/${projectId}/keyword-groups`, ...(params ? [params] : [])
    ] as const;
    }


export const getKeywordGroupsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError = void>(projectId: string,
    params: KeywordGroupsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getKeywordGroupsControllerListQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof keywordGroupsControllerList>>> = ({ signal }) => keywordGroupsControllerList(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type KeywordGroupsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof keywordGroupsControllerList>>>
export type KeywordGroupsControllerListQueryError = void


export function useKeywordGroupsControllerList<TData = Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError = void>(
 projectId: string,
    params: KeywordGroupsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof keywordGroupsControllerList>>,
          TError,
          Awaited<ReturnType<typeof keywordGroupsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useKeywordGroupsControllerList<TData = Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError = void>(
 projectId: string,
    params: KeywordGroupsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof keywordGroupsControllerList>>,
          TError,
          Awaited<ReturnType<typeof keywordGroupsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useKeywordGroupsControllerList<TData = Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError = void>(
 projectId: string,
    params: KeywordGroupsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useKeywordGroupsControllerList<TData = Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError = void>(
 projectId: string,
    params: KeywordGroupsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getKeywordGroupsControllerListQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type keywordGroupsControllerCreateResponse201 = {
  data: KeywordGroupResponseDto
  status: 201
}

export type keywordGroupsControllerCreateResponse403 = {
  data: void
  status: 403
}

export type keywordGroupsControllerCreateResponse404 = {
  data: void
  status: 404
}

export type keywordGroupsControllerCreateResponseSuccess = (keywordGroupsControllerCreateResponse201) & {
  headers: Headers;
};
export type keywordGroupsControllerCreateResponseError = (keywordGroupsControllerCreateResponse403 | keywordGroupsControllerCreateResponse404) & {
  headers: Headers;
};

export type keywordGroupsControllerCreateResponse = (keywordGroupsControllerCreateResponseSuccess | keywordGroupsControllerCreateResponseError)

export const getKeywordGroupsControllerCreateUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/keyword-groups`
}

export const keywordGroupsControllerCreate = async (projectId: string,
    createKeywordGroupDto: CreateKeywordGroupDto, options?: Parameters<typeof customFetch>[1]): Promise<keywordGroupsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<keywordGroupsControllerCreateResponse>(getKeywordGroupsControllerCreateUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createKeywordGroupDto)
  }
);}





export const getKeywordGroupsControllerCreateMutationKey = () => ['keywordGroupsControllerCreate'] as const;

export const getKeywordGroupsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerCreate>>, TError,KeywordGroupsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerCreate>>, TError,KeywordGroupsControllerCreateMutationVariables, TContext> => {

const mutationKey = getKeywordGroupsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof keywordGroupsControllerCreate>>, KeywordGroupsControllerCreateMutationVariables> = (props) => {
          const {projectId,data} = props ?? {};

          return  keywordGroupsControllerCreate(projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type KeywordGroupsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof keywordGroupsControllerCreate>>>
    export type KeywordGroupsControllerCreateMutationBody = CreateKeywordGroupDto
    export type KeywordGroupsControllerCreateMutationError = void
    export type KeywordGroupsControllerCreateMutationVariables = {projectId: string;data: CreateKeywordGroupDto}

    export const useKeywordGroupsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerCreate>>, TError,KeywordGroupsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof keywordGroupsControllerCreate>>,
        TError,
        KeywordGroupsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getKeywordGroupsControllerCreateMutationOptions(options), queryClient);
    }
    export type keywordGroupsControllerFindOneResponse200 = {
  data: KeywordGroupResponseDto
  status: 200
}

export type keywordGroupsControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type keywordGroupsControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type keywordGroupsControllerFindOneResponseSuccess = (keywordGroupsControllerFindOneResponse200) & {
  headers: Headers;
};
export type keywordGroupsControllerFindOneResponseError = (keywordGroupsControllerFindOneResponse403 | keywordGroupsControllerFindOneResponse404) & {
  headers: Headers;
};

export type keywordGroupsControllerFindOneResponse = (keywordGroupsControllerFindOneResponseSuccess | keywordGroupsControllerFindOneResponseError)

export const getKeywordGroupsControllerFindOneUrl = (projectId: string,
    groupId: string,) => {




  return `/api/v1/projects/${projectId}/keyword-groups/${groupId}`
}

export const keywordGroupsControllerFindOne = async (projectId: string,
    groupId: string, options?: Parameters<typeof customFetch>[1]): Promise<keywordGroupsControllerFindOneResponse> => {

  return customFetch<keywordGroupsControllerFindOneResponse>(getKeywordGroupsControllerFindOneUrl(projectId,groupId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getKeywordGroupsControllerFindOneQueryKey = (projectId: string,
    groupId: string,) => {
    return [
    `/api/v1/projects/${projectId}/keyword-groups/${groupId}`
    ] as const;
    }


export const getKeywordGroupsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError = void>(projectId: string,
    groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getKeywordGroupsControllerFindOneQueryKey(projectId,groupId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>> = ({ signal }) => keywordGroupsControllerFindOne(projectId,groupId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && groupId !== null && groupId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type KeywordGroupsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>>
export type KeywordGroupsControllerFindOneQueryError = void


export function useKeywordGroupsControllerFindOne<TData = Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError = void>(
 projectId: string,
    groupId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useKeywordGroupsControllerFindOne<TData = Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError = void>(
 projectId: string,
    groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useKeywordGroupsControllerFindOne<TData = Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError = void>(
 projectId: string,
    groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useKeywordGroupsControllerFindOne<TData = Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError = void>(
 projectId: string,
    groupId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof keywordGroupsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getKeywordGroupsControllerFindOneQueryOptions(projectId,groupId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type keywordGroupsControllerUpdateResponse200 = {
  data: KeywordGroupResponseDto
  status: 200
}

export type keywordGroupsControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type keywordGroupsControllerUpdateResponse404 = {
  data: void
  status: 404
}

export type keywordGroupsControllerUpdateResponseSuccess = (keywordGroupsControllerUpdateResponse200) & {
  headers: Headers;
};
export type keywordGroupsControllerUpdateResponseError = (keywordGroupsControllerUpdateResponse403 | keywordGroupsControllerUpdateResponse404) & {
  headers: Headers;
};

export type keywordGroupsControllerUpdateResponse = (keywordGroupsControllerUpdateResponseSuccess | keywordGroupsControllerUpdateResponseError)

export const getKeywordGroupsControllerUpdateUrl = (projectId: string,
    groupId: string,) => {




  return `/api/v1/projects/${projectId}/keyword-groups/${groupId}`
}

export const keywordGroupsControllerUpdate = async (projectId: string,
    groupId: string,
    updateKeywordGroupDto: UpdateKeywordGroupDto, options?: Parameters<typeof customFetch>[1]): Promise<keywordGroupsControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<keywordGroupsControllerUpdateResponse>(getKeywordGroupsControllerUpdateUrl(projectId,groupId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateKeywordGroupDto)
  }
);}





export const getKeywordGroupsControllerUpdateMutationKey = () => ['keywordGroupsControllerUpdate'] as const;

export const getKeywordGroupsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerUpdate>>, TError,KeywordGroupsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerUpdate>>, TError,KeywordGroupsControllerUpdateMutationVariables, TContext> => {

const mutationKey = getKeywordGroupsControllerUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof keywordGroupsControllerUpdate>>, KeywordGroupsControllerUpdateMutationVariables> = (props) => {
          const {projectId,groupId,data} = props ?? {};

          return  keywordGroupsControllerUpdate(projectId,groupId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type KeywordGroupsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof keywordGroupsControllerUpdate>>>
    export type KeywordGroupsControllerUpdateMutationBody = UpdateKeywordGroupDto
    export type KeywordGroupsControllerUpdateMutationError = void
    export type KeywordGroupsControllerUpdateMutationVariables = {projectId: string;groupId: string;data: UpdateKeywordGroupDto}

    export const useKeywordGroupsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerUpdate>>, TError,KeywordGroupsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof keywordGroupsControllerUpdate>>,
        TError,
        KeywordGroupsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getKeywordGroupsControllerUpdateMutationOptions(options), queryClient);
    }
    export type keywordGroupsControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type keywordGroupsControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type keywordGroupsControllerDeleteResponse404 = {
  data: void
  status: 404
}

export type keywordGroupsControllerDeleteResponseSuccess = (keywordGroupsControllerDeleteResponse204) & {
  headers: Headers;
};
export type keywordGroupsControllerDeleteResponseError = (keywordGroupsControllerDeleteResponse403 | keywordGroupsControllerDeleteResponse404) & {
  headers: Headers;
};

export type keywordGroupsControllerDeleteResponse = (keywordGroupsControllerDeleteResponseSuccess | keywordGroupsControllerDeleteResponseError)

export const getKeywordGroupsControllerDeleteUrl = (projectId: string,
    groupId: string,) => {




  return `/api/v1/projects/${projectId}/keyword-groups/${groupId}`
}

export const keywordGroupsControllerDelete = async (projectId: string,
    groupId: string, options?: Parameters<typeof customFetch>[1]): Promise<keywordGroupsControllerDeleteResponse> => {

  return customFetch<keywordGroupsControllerDeleteResponse>(getKeywordGroupsControllerDeleteUrl(projectId,groupId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getKeywordGroupsControllerDeleteMutationKey = () => ['keywordGroupsControllerDelete'] as const;

export const getKeywordGroupsControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerDelete>>, TError,KeywordGroupsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerDelete>>, TError,KeywordGroupsControllerDeleteMutationVariables, TContext> => {

const mutationKey = getKeywordGroupsControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof keywordGroupsControllerDelete>>, KeywordGroupsControllerDeleteMutationVariables> = (props) => {
          const {projectId,groupId} = props ?? {};

          return  keywordGroupsControllerDelete(projectId,groupId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type KeywordGroupsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof keywordGroupsControllerDelete>>>

    export type KeywordGroupsControllerDeleteMutationError = void
    export type KeywordGroupsControllerDeleteMutationVariables = {projectId: string;groupId: string}

    export const useKeywordGroupsControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof keywordGroupsControllerDelete>>, TError,KeywordGroupsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof keywordGroupsControllerDelete>>,
        TError,
        KeywordGroupsControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getKeywordGroupsControllerDeleteMutationOptions(options), queryClient);
    }
    export type trackedKeywordsControllerListResponse200 = {
  data: TrackedKeywordListResponseDto
  status: 200
}

export type trackedKeywordsControllerListResponse403 = {
  data: void
  status: 403
}

export type trackedKeywordsControllerListResponse404 = {
  data: void
  status: 404
}

export type trackedKeywordsControllerListResponseSuccess = (trackedKeywordsControllerListResponse200) & {
  headers: Headers;
};
export type trackedKeywordsControllerListResponseError = (trackedKeywordsControllerListResponse403 | trackedKeywordsControllerListResponse404) & {
  headers: Headers;
};

export type trackedKeywordsControllerListResponse = (trackedKeywordsControllerListResponseSuccess | trackedKeywordsControllerListResponseError)

export const getTrackedKeywordsControllerListUrl = (projectId: string,
    params: TrackedKeywordsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/keywords?${stringifiedParams}` : `/api/v1/projects/${projectId}/keywords`
}

export const trackedKeywordsControllerList = async (projectId: string,
    params: TrackedKeywordsControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<trackedKeywordsControllerListResponse> => {

  return customFetch<trackedKeywordsControllerListResponse>(getTrackedKeywordsControllerListUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTrackedKeywordsControllerListQueryKey = (projectId: string,
    params?: TrackedKeywordsControllerListParams,) => {
    return [
    `/api/v1/projects/${projectId}/keywords`, ...(params ? [params] : [])
    ] as const;
    }


export const getTrackedKeywordsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError = void>(projectId: string,
    params: TrackedKeywordsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackedKeywordsControllerListQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackedKeywordsControllerList>>> = ({ signal }) => trackedKeywordsControllerList(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackedKeywordsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof trackedKeywordsControllerList>>>
export type TrackedKeywordsControllerListQueryError = void


export function useTrackedKeywordsControllerList<TData = Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError = void>(
 projectId: string,
    params: TrackedKeywordsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackedKeywordsControllerList>>,
          TError,
          Awaited<ReturnType<typeof trackedKeywordsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackedKeywordsControllerList<TData = Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError = void>(
 projectId: string,
    params: TrackedKeywordsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackedKeywordsControllerList>>,
          TError,
          Awaited<ReturnType<typeof trackedKeywordsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackedKeywordsControllerList<TData = Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError = void>(
 projectId: string,
    params: TrackedKeywordsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackedKeywordsControllerList<TData = Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError = void>(
 projectId: string,
    params: TrackedKeywordsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackedKeywordsControllerListQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type trackedKeywordsControllerCreateResponse201 = {
  data: TrackedKeywordResponseDto
  status: 201
}

export type trackedKeywordsControllerCreateResponse403 = {
  data: void
  status: 403
}

export type trackedKeywordsControllerCreateResponse404 = {
  data: void
  status: 404
}

export type trackedKeywordsControllerCreateResponseSuccess = (trackedKeywordsControllerCreateResponse201) & {
  headers: Headers;
};
export type trackedKeywordsControllerCreateResponseError = (trackedKeywordsControllerCreateResponse403 | trackedKeywordsControllerCreateResponse404) & {
  headers: Headers;
};

export type trackedKeywordsControllerCreateResponse = (trackedKeywordsControllerCreateResponseSuccess | trackedKeywordsControllerCreateResponseError)

export const getTrackedKeywordsControllerCreateUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/keywords`
}

export const trackedKeywordsControllerCreate = async (projectId: string,
    createTrackedKeywordDto: CreateTrackedKeywordDto, options?: Parameters<typeof customFetch>[1]): Promise<trackedKeywordsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<trackedKeywordsControllerCreateResponse>(getTrackedKeywordsControllerCreateUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createTrackedKeywordDto)
  }
);}





export const getTrackedKeywordsControllerCreateMutationKey = () => ['trackedKeywordsControllerCreate'] as const;

export const getTrackedKeywordsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerCreate>>, TError,TrackedKeywordsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerCreate>>, TError,TrackedKeywordsControllerCreateMutationVariables, TContext> => {

const mutationKey = getTrackedKeywordsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackedKeywordsControllerCreate>>, TrackedKeywordsControllerCreateMutationVariables> = (props) => {
          const {projectId,data} = props ?? {};

          return  trackedKeywordsControllerCreate(projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackedKeywordsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof trackedKeywordsControllerCreate>>>
    export type TrackedKeywordsControllerCreateMutationBody = CreateTrackedKeywordDto
    export type TrackedKeywordsControllerCreateMutationError = void
    export type TrackedKeywordsControllerCreateMutationVariables = {projectId: string;data: CreateTrackedKeywordDto}

    export const useTrackedKeywordsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerCreate>>, TError,TrackedKeywordsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackedKeywordsControllerCreate>>,
        TError,
        TrackedKeywordsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getTrackedKeywordsControllerCreateMutationOptions(options), queryClient);
    }
    export type trackedKeywordsControllerSuggestionsResponse200 = {
  data: KeywordSuggestionsResponseDto
  status: 200
}

export type trackedKeywordsControllerSuggestionsResponse403 = {
  data: void
  status: 403
}

export type trackedKeywordsControllerSuggestionsResponse404 = {
  data: void
  status: 404
}

export type trackedKeywordsControllerSuggestionsResponseSuccess = (trackedKeywordsControllerSuggestionsResponse200) & {
  headers: Headers;
};
export type trackedKeywordsControllerSuggestionsResponseError = (trackedKeywordsControllerSuggestionsResponse403 | trackedKeywordsControllerSuggestionsResponse404) & {
  headers: Headers;
};

export type trackedKeywordsControllerSuggestionsResponse = (trackedKeywordsControllerSuggestionsResponseSuccess | trackedKeywordsControllerSuggestionsResponseError)

export const getTrackedKeywordsControllerSuggestionsUrl = (projectId: string,
    params: TrackedKeywordsControllerSuggestionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/keywords/suggestions?${stringifiedParams}` : `/api/v1/projects/${projectId}/keywords/suggestions`
}

/**
 * @summary Son 28 günde gösterimi yüksek, takipte olmayan GSC sorguları.
 */
export const trackedKeywordsControllerSuggestions = async (projectId: string,
    params: TrackedKeywordsControllerSuggestionsParams, options?: Parameters<typeof customFetch>[1]): Promise<trackedKeywordsControllerSuggestionsResponse> => {

  return customFetch<trackedKeywordsControllerSuggestionsResponse>(getTrackedKeywordsControllerSuggestionsUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTrackedKeywordsControllerSuggestionsQueryKey = (projectId: string,
    params?: TrackedKeywordsControllerSuggestionsParams,) => {
    return [
    `/api/v1/projects/${projectId}/keywords/suggestions`, ...(params ? [params] : [])
    ] as const;
    }


export const getTrackedKeywordsControllerSuggestionsQueryOptions = <TData = Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError = void>(projectId: string,
    params: TrackedKeywordsControllerSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackedKeywordsControllerSuggestionsQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>> = ({ signal }) => trackedKeywordsControllerSuggestions(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackedKeywordsControllerSuggestionsQueryResult = NonNullable<Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>>
export type TrackedKeywordsControllerSuggestionsQueryError = void


export function useTrackedKeywordsControllerSuggestions<TData = Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError = void>(
 projectId: string,
    params: TrackedKeywordsControllerSuggestionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>,
          TError,
          Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackedKeywordsControllerSuggestions<TData = Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError = void>(
 projectId: string,
    params: TrackedKeywordsControllerSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>,
          TError,
          Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackedKeywordsControllerSuggestions<TData = Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError = void>(
 projectId: string,
    params: TrackedKeywordsControllerSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Son 28 günde gösterimi yüksek, takipte olmayan GSC sorguları.
 */

export function useTrackedKeywordsControllerSuggestions<TData = Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError = void>(
 projectId: string,
    params: TrackedKeywordsControllerSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerSuggestions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackedKeywordsControllerSuggestionsQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type trackedKeywordsControllerBulkAddResponse201 = {
  data: BulkAddKeywordsResponseDto
  status: 201
}

export type trackedKeywordsControllerBulkAddResponse403 = {
  data: void
  status: 403
}

export type trackedKeywordsControllerBulkAddResponse404 = {
  data: void
  status: 404
}

export type trackedKeywordsControllerBulkAddResponseSuccess = (trackedKeywordsControllerBulkAddResponse201) & {
  headers: Headers;
};
export type trackedKeywordsControllerBulkAddResponseError = (trackedKeywordsControllerBulkAddResponse403 | trackedKeywordsControllerBulkAddResponse404) & {
  headers: Headers;
};

export type trackedKeywordsControllerBulkAddResponse = (trackedKeywordsControllerBulkAddResponseSuccess | trackedKeywordsControllerBulkAddResponseError)

export const getTrackedKeywordsControllerBulkAddUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/keywords/bulk`
}

/**
 * @summary Satır satır metin ya da CSV; tek transaction, satır numaralı rapor döner.
 */
export const trackedKeywordsControllerBulkAdd = async (projectId: string,
    bulkAddKeywordsDto: BulkAddKeywordsDto, options?: Parameters<typeof customFetch>[1]): Promise<trackedKeywordsControllerBulkAddResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<trackedKeywordsControllerBulkAddResponse>(getTrackedKeywordsControllerBulkAddUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(bulkAddKeywordsDto)
  }
);}





export const getTrackedKeywordsControllerBulkAddMutationKey = () => ['trackedKeywordsControllerBulkAdd'] as const;

export const getTrackedKeywordsControllerBulkAddMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerBulkAdd>>, TError,TrackedKeywordsControllerBulkAddMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerBulkAdd>>, TError,TrackedKeywordsControllerBulkAddMutationVariables, TContext> => {

const mutationKey = getTrackedKeywordsControllerBulkAddMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackedKeywordsControllerBulkAdd>>, TrackedKeywordsControllerBulkAddMutationVariables> = (props) => {
          const {projectId,data} = props ?? {};

          return  trackedKeywordsControllerBulkAdd(projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackedKeywordsControllerBulkAddMutationResult = NonNullable<Awaited<ReturnType<typeof trackedKeywordsControllerBulkAdd>>>
    export type TrackedKeywordsControllerBulkAddMutationBody = BulkAddKeywordsDto
    export type TrackedKeywordsControllerBulkAddMutationError = void
    export type TrackedKeywordsControllerBulkAddMutationVariables = {projectId: string;data: BulkAddKeywordsDto}

    /**
 * @summary Satır satır metin ya da CSV; tek transaction, satır numaralı rapor döner.
 */
export const useTrackedKeywordsControllerBulkAdd = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerBulkAdd>>, TError,TrackedKeywordsControllerBulkAddMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackedKeywordsControllerBulkAdd>>,
        TError,
        TrackedKeywordsControllerBulkAddMutationVariables,
        TContext
      > => {
      return useMutation(getTrackedKeywordsControllerBulkAddMutationOptions(options), queryClient);
    }
    export type trackedKeywordsControllerFindOneResponse200 = {
  data: TrackedKeywordResponseDto
  status: 200
}

export type trackedKeywordsControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type trackedKeywordsControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type trackedKeywordsControllerFindOneResponseSuccess = (trackedKeywordsControllerFindOneResponse200) & {
  headers: Headers;
};
export type trackedKeywordsControllerFindOneResponseError = (trackedKeywordsControllerFindOneResponse403 | trackedKeywordsControllerFindOneResponse404) & {
  headers: Headers;
};

export type trackedKeywordsControllerFindOneResponse = (trackedKeywordsControllerFindOneResponseSuccess | trackedKeywordsControllerFindOneResponseError)

export const getTrackedKeywordsControllerFindOneUrl = (projectId: string,
    keywordId: string,) => {




  return `/api/v1/projects/${projectId}/keywords/${keywordId}`
}

export const trackedKeywordsControllerFindOne = async (projectId: string,
    keywordId: string, options?: Parameters<typeof customFetch>[1]): Promise<trackedKeywordsControllerFindOneResponse> => {

  return customFetch<trackedKeywordsControllerFindOneResponse>(getTrackedKeywordsControllerFindOneUrl(projectId,keywordId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getTrackedKeywordsControllerFindOneQueryKey = (projectId: string,
    keywordId: string,) => {
    return [
    `/api/v1/projects/${projectId}/keywords/${keywordId}`
    ] as const;
    }


export const getTrackedKeywordsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError = void>(projectId: string,
    keywordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTrackedKeywordsControllerFindOneQueryKey(projectId,keywordId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>> = ({ signal }) => trackedKeywordsControllerFindOne(projectId,keywordId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && keywordId !== null && keywordId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TrackedKeywordsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>>
export type TrackedKeywordsControllerFindOneQueryError = void


export function useTrackedKeywordsControllerFindOne<TData = Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError = void>(
 projectId: string,
    keywordId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackedKeywordsControllerFindOne<TData = Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError = void>(
 projectId: string,
    keywordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTrackedKeywordsControllerFindOne<TData = Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError = void>(
 projectId: string,
    keywordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useTrackedKeywordsControllerFindOne<TData = Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError = void>(
 projectId: string,
    keywordId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof trackedKeywordsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTrackedKeywordsControllerFindOneQueryOptions(projectId,keywordId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type trackedKeywordsControllerUpdateResponse200 = {
  data: TrackedKeywordResponseDto
  status: 200
}

export type trackedKeywordsControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type trackedKeywordsControllerUpdateResponse404 = {
  data: void
  status: 404
}

export type trackedKeywordsControllerUpdateResponseSuccess = (trackedKeywordsControllerUpdateResponse200) & {
  headers: Headers;
};
export type trackedKeywordsControllerUpdateResponseError = (trackedKeywordsControllerUpdateResponse403 | trackedKeywordsControllerUpdateResponse404) & {
  headers: Headers;
};

export type trackedKeywordsControllerUpdateResponse = (trackedKeywordsControllerUpdateResponseSuccess | trackedKeywordsControllerUpdateResponseError)

export const getTrackedKeywordsControllerUpdateUrl = (projectId: string,
    keywordId: string,) => {




  return `/api/v1/projects/${projectId}/keywords/${keywordId}`
}

export const trackedKeywordsControllerUpdate = async (projectId: string,
    keywordId: string,
    updateTrackedKeywordDto: UpdateTrackedKeywordDto, options?: Parameters<typeof customFetch>[1]): Promise<trackedKeywordsControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<trackedKeywordsControllerUpdateResponse>(getTrackedKeywordsControllerUpdateUrl(projectId,keywordId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateTrackedKeywordDto)
  }
);}





export const getTrackedKeywordsControllerUpdateMutationKey = () => ['trackedKeywordsControllerUpdate'] as const;

export const getTrackedKeywordsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerUpdate>>, TError,TrackedKeywordsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerUpdate>>, TError,TrackedKeywordsControllerUpdateMutationVariables, TContext> => {

const mutationKey = getTrackedKeywordsControllerUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackedKeywordsControllerUpdate>>, TrackedKeywordsControllerUpdateMutationVariables> = (props) => {
          const {projectId,keywordId,data} = props ?? {};

          return  trackedKeywordsControllerUpdate(projectId,keywordId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackedKeywordsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof trackedKeywordsControllerUpdate>>>
    export type TrackedKeywordsControllerUpdateMutationBody = UpdateTrackedKeywordDto
    export type TrackedKeywordsControllerUpdateMutationError = void
    export type TrackedKeywordsControllerUpdateMutationVariables = {projectId: string;keywordId: string;data: UpdateTrackedKeywordDto}

    export const useTrackedKeywordsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerUpdate>>, TError,TrackedKeywordsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackedKeywordsControllerUpdate>>,
        TError,
        TrackedKeywordsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getTrackedKeywordsControllerUpdateMutationOptions(options), queryClient);
    }
    export type trackedKeywordsControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type trackedKeywordsControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type trackedKeywordsControllerDeleteResponse404 = {
  data: void
  status: 404
}

export type trackedKeywordsControllerDeleteResponseSuccess = (trackedKeywordsControllerDeleteResponse204) & {
  headers: Headers;
};
export type trackedKeywordsControllerDeleteResponseError = (trackedKeywordsControllerDeleteResponse403 | trackedKeywordsControllerDeleteResponse404) & {
  headers: Headers;
};

export type trackedKeywordsControllerDeleteResponse = (trackedKeywordsControllerDeleteResponseSuccess | trackedKeywordsControllerDeleteResponseError)

export const getTrackedKeywordsControllerDeleteUrl = (projectId: string,
    keywordId: string,) => {




  return `/api/v1/projects/${projectId}/keywords/${keywordId}`
}

export const trackedKeywordsControllerDelete = async (projectId: string,
    keywordId: string, options?: Parameters<typeof customFetch>[1]): Promise<trackedKeywordsControllerDeleteResponse> => {

  return customFetch<trackedKeywordsControllerDeleteResponse>(getTrackedKeywordsControllerDeleteUrl(projectId,keywordId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getTrackedKeywordsControllerDeleteMutationKey = () => ['trackedKeywordsControllerDelete'] as const;

export const getTrackedKeywordsControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerDelete>>, TError,TrackedKeywordsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerDelete>>, TError,TrackedKeywordsControllerDeleteMutationVariables, TContext> => {

const mutationKey = getTrackedKeywordsControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof trackedKeywordsControllerDelete>>, TrackedKeywordsControllerDeleteMutationVariables> = (props) => {
          const {projectId,keywordId} = props ?? {};

          return  trackedKeywordsControllerDelete(projectId,keywordId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TrackedKeywordsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof trackedKeywordsControllerDelete>>>

    export type TrackedKeywordsControllerDeleteMutationError = void
    export type TrackedKeywordsControllerDeleteMutationVariables = {projectId: string;keywordId: string}

    export const useTrackedKeywordsControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof trackedKeywordsControllerDelete>>, TError,TrackedKeywordsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof trackedKeywordsControllerDelete>>,
        TError,
        TrackedKeywordsControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getTrackedKeywordsControllerDeleteMutationOptions(options), queryClient);
    }
