/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GscControllerOverviewParams,
  GscControllerPageQueriesParams,
  GscControllerPagesParams,
  GscControllerQueriesParams,
  GscControllerQueryPagesParams,
  GscOverviewResponseDto,
  GscPageListResponseDto,
  GscQueryListResponseDto,
  GscSyncResponseDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type gscControllerTriggerSyncResponse202 = {
  data: GscSyncResponseDto
  status: 202
}

export type gscControllerTriggerSyncResponse403 = {
  data: void
  status: 403
}

export type gscControllerTriggerSyncResponse404 = {
  data: void
  status: 404
}

export type gscControllerTriggerSyncResponse409 = {
  data: void
  status: 409
}

export type gscControllerTriggerSyncResponseSuccess = (gscControllerTriggerSyncResponse202) & {
  headers: Headers;
};
export type gscControllerTriggerSyncResponseError = (gscControllerTriggerSyncResponse403 | gscControllerTriggerSyncResponse404 | gscControllerTriggerSyncResponse409) & {
  headers: Headers;
};

export type gscControllerTriggerSyncResponse = (gscControllerTriggerSyncResponseSuccess | gscControllerTriggerSyncResponseError)

export const getGscControllerTriggerSyncUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/sync/gsc`
}

/**
 * @summary Son 5 günü yeniden çeker; iş kuyrukta yapılır (CLAUDE.md kural 6).
 */
export const gscControllerTriggerSync = async (projectId: string, options?: Parameters<typeof customFetch>[1]): Promise<gscControllerTriggerSyncResponse> => {

  return customFetch<gscControllerTriggerSyncResponse>(getGscControllerTriggerSyncUrl(projectId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getGscControllerTriggerSyncMutationKey = () => ['gscControllerTriggerSync'] as const;

export const getGscControllerTriggerSyncMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gscControllerTriggerSync>>, TError,GscControllerTriggerSyncMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof gscControllerTriggerSync>>, TError,GscControllerTriggerSyncMutationVariables, TContext> => {

const mutationKey = getGscControllerTriggerSyncMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof gscControllerTriggerSync>>, GscControllerTriggerSyncMutationVariables> = (props) => {
          const {projectId} = props ?? {};

          return  gscControllerTriggerSync(projectId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GscControllerTriggerSyncMutationResult = NonNullable<Awaited<ReturnType<typeof gscControllerTriggerSync>>>

    export type GscControllerTriggerSyncMutationError = void
    export type GscControllerTriggerSyncMutationVariables = {projectId: string}

    /**
 * @summary Son 5 günü yeniden çeker; iş kuyrukta yapılır (CLAUDE.md kural 6).
 */
export const useGscControllerTriggerSync = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof gscControllerTriggerSync>>, TError,GscControllerTriggerSyncMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof gscControllerTriggerSync>>,
        TError,
        GscControllerTriggerSyncMutationVariables,
        TContext
      > => {
      return useMutation(getGscControllerTriggerSyncMutationOptions(options), queryClient);
    }
    export type gscControllerOverviewResponse200 = {
  data: GscOverviewResponseDto
  status: 200
}

export type gscControllerOverviewResponse400 = {
  data: void
  status: 400
}

export type gscControllerOverviewResponse403 = {
  data: void
  status: 403
}

export type gscControllerOverviewResponse404 = {
  data: void
  status: 404
}

export type gscControllerOverviewResponseSuccess = (gscControllerOverviewResponse200) & {
  headers: Headers;
};
export type gscControllerOverviewResponseError = (gscControllerOverviewResponse400 | gscControllerOverviewResponse403 | gscControllerOverviewResponse404) & {
  headers: Headers;
};

export type gscControllerOverviewResponse = (gscControllerOverviewResponseSuccess | gscControllerOverviewResponseError)

export const getGscControllerOverviewUrl = (projectId: string,
    params?: GscControllerOverviewParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/gsc/overview?${stringifiedParams}` : `/api/v1/projects/${projectId}/gsc/overview`
}

/**
 * @summary Site toplamları ve günlük seri (`gsc_site_daily`); `compare` ile karşılaştırma dönemi.
 */
export const gscControllerOverview = async (projectId: string,
    params?: GscControllerOverviewParams, options?: Parameters<typeof customFetch>[1]): Promise<gscControllerOverviewResponse> => {

  return customFetch<gscControllerOverviewResponse>(getGscControllerOverviewUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGscControllerOverviewQueryKey = (projectId: string,
    params?: GscControllerOverviewParams,) => {
    return [
    `/api/v1/projects/${projectId}/gsc/overview`, ...(params ? [params] : [])
    ] as const;
    }


export const getGscControllerOverviewQueryOptions = <TData = Awaited<ReturnType<typeof gscControllerOverview>>, TError = void>(projectId: string,
    params?: GscControllerOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerOverview>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGscControllerOverviewQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof gscControllerOverview>>> = ({ signal }) => gscControllerOverview(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gscControllerOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GscControllerOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof gscControllerOverview>>>
export type GscControllerOverviewQueryError = void


export function useGscControllerOverview<TData = Awaited<ReturnType<typeof gscControllerOverview>>, TError = void>(
 projectId: string,
    params: undefined |  GscControllerOverviewParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerOverview>>,
          TError,
          Awaited<ReturnType<typeof gscControllerOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerOverview<TData = Awaited<ReturnType<typeof gscControllerOverview>>, TError = void>(
 projectId: string,
    params?: GscControllerOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerOverview>>,
          TError,
          Awaited<ReturnType<typeof gscControllerOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerOverview<TData = Awaited<ReturnType<typeof gscControllerOverview>>, TError = void>(
 projectId: string,
    params?: GscControllerOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerOverview>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Site toplamları ve günlük seri (`gsc_site_daily`); `compare` ile karşılaştırma dönemi.
 */

export function useGscControllerOverview<TData = Awaited<ReturnType<typeof gscControllerOverview>>, TError = void>(
 projectId: string,
    params?: GscControllerOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerOverview>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGscControllerOverviewQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type gscControllerQueriesResponse200 = {
  data: GscQueryListResponseDto
  status: 200
}

export type gscControllerQueriesResponse400 = {
  data: void
  status: 400
}

export type gscControllerQueriesResponse403 = {
  data: void
  status: 403
}

export type gscControllerQueriesResponse404 = {
  data: void
  status: 404
}

export type gscControllerQueriesResponseSuccess = (gscControllerQueriesResponse200) & {
  headers: Headers;
};
export type gscControllerQueriesResponseError = (gscControllerQueriesResponse400 | gscControllerQueriesResponse403 | gscControllerQueriesResponse404) & {
  headers: Headers;
};

export type gscControllerQueriesResponse = (gscControllerQueriesResponseSuccess | gscControllerQueriesResponseError)

export const getGscControllerQueriesUrl = (projectId: string,
    params: GscControllerQueriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/gsc/queries?${stringifiedParams}` : `/api/v1/projects/${projectId}/gsc/queries`
}

/**
 * @summary Sorgu bazında toplanmış tablo (`gsc_daily`).
 */
export const gscControllerQueries = async (projectId: string,
    params: GscControllerQueriesParams, options?: Parameters<typeof customFetch>[1]): Promise<gscControllerQueriesResponse> => {

  return customFetch<gscControllerQueriesResponse>(getGscControllerQueriesUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGscControllerQueriesQueryKey = (projectId: string,
    params?: GscControllerQueriesParams,) => {
    return [
    `/api/v1/projects/${projectId}/gsc/queries`, ...(params ? [params] : [])
    ] as const;
    }


export const getGscControllerQueriesQueryOptions = <TData = Awaited<ReturnType<typeof gscControllerQueries>>, TError = void>(projectId: string,
    params: GscControllerQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGscControllerQueriesQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof gscControllerQueries>>> = ({ signal }) => gscControllerQueries(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GscControllerQueriesQueryResult = NonNullable<Awaited<ReturnType<typeof gscControllerQueries>>>
export type GscControllerQueriesQueryError = void


export function useGscControllerQueries<TData = Awaited<ReturnType<typeof gscControllerQueries>>, TError = void>(
 projectId: string,
    params: GscControllerQueriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerQueries>>,
          TError,
          Awaited<ReturnType<typeof gscControllerQueries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerQueries<TData = Awaited<ReturnType<typeof gscControllerQueries>>, TError = void>(
 projectId: string,
    params: GscControllerQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerQueries>>,
          TError,
          Awaited<ReturnType<typeof gscControllerQueries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerQueries<TData = Awaited<ReturnType<typeof gscControllerQueries>>, TError = void>(
 projectId: string,
    params: GscControllerQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sorgu bazında toplanmış tablo (`gsc_daily`).
 */

export function useGscControllerQueries<TData = Awaited<ReturnType<typeof gscControllerQueries>>, TError = void>(
 projectId: string,
    params: GscControllerQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGscControllerQueriesQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type gscControllerPagesResponse200 = {
  data: GscPageListResponseDto
  status: 200
}

export type gscControllerPagesResponse400 = {
  data: void
  status: 400
}

export type gscControllerPagesResponse403 = {
  data: void
  status: 403
}

export type gscControllerPagesResponse404 = {
  data: void
  status: 404
}

export type gscControllerPagesResponseSuccess = (gscControllerPagesResponse200) & {
  headers: Headers;
};
export type gscControllerPagesResponseError = (gscControllerPagesResponse400 | gscControllerPagesResponse403 | gscControllerPagesResponse404) & {
  headers: Headers;
};

export type gscControllerPagesResponse = (gscControllerPagesResponseSuccess | gscControllerPagesResponseError)

export const getGscControllerPagesUrl = (projectId: string,
    params: GscControllerPagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/gsc/pages?${stringifiedParams}` : `/api/v1/projects/${projectId}/gsc/pages`
}

/**
 * @summary Sayfa bazında toplanmış tablo (`gsc_page_daily`).
 */
export const gscControllerPages = async (projectId: string,
    params: GscControllerPagesParams, options?: Parameters<typeof customFetch>[1]): Promise<gscControllerPagesResponse> => {

  return customFetch<gscControllerPagesResponse>(getGscControllerPagesUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGscControllerPagesQueryKey = (projectId: string,
    params?: GscControllerPagesParams,) => {
    return [
    `/api/v1/projects/${projectId}/gsc/pages`, ...(params ? [params] : [])
    ] as const;
    }


export const getGscControllerPagesQueryOptions = <TData = Awaited<ReturnType<typeof gscControllerPages>>, TError = void>(projectId: string,
    params: GscControllerPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGscControllerPagesQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof gscControllerPages>>> = ({ signal }) => gscControllerPages(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gscControllerPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GscControllerPagesQueryResult = NonNullable<Awaited<ReturnType<typeof gscControllerPages>>>
export type GscControllerPagesQueryError = void


export function useGscControllerPages<TData = Awaited<ReturnType<typeof gscControllerPages>>, TError = void>(
 projectId: string,
    params: GscControllerPagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerPages>>,
          TError,
          Awaited<ReturnType<typeof gscControllerPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerPages<TData = Awaited<ReturnType<typeof gscControllerPages>>, TError = void>(
 projectId: string,
    params: GscControllerPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerPages>>,
          TError,
          Awaited<ReturnType<typeof gscControllerPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerPages<TData = Awaited<ReturnType<typeof gscControllerPages>>, TError = void>(
 projectId: string,
    params: GscControllerPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Sayfa bazında toplanmış tablo (`gsc_page_daily`).
 */

export function useGscControllerPages<TData = Awaited<ReturnType<typeof gscControllerPages>>, TError = void>(
 projectId: string,
    params: GscControllerPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGscControllerPagesQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type gscControllerQueryPagesResponse200 = {
  data: GscPageListResponseDto
  status: 200
}

export type gscControllerQueryPagesResponse400 = {
  data: void
  status: 400
}

export type gscControllerQueryPagesResponse403 = {
  data: void
  status: 403
}

export type gscControllerQueryPagesResponse404 = {
  data: void
  status: 404
}

export type gscControllerQueryPagesResponseSuccess = (gscControllerQueryPagesResponse200) & {
  headers: Headers;
};
export type gscControllerQueryPagesResponseError = (gscControllerQueryPagesResponse400 | gscControllerQueryPagesResponse403 | gscControllerQueryPagesResponse404) & {
  headers: Headers;
};

export type gscControllerQueryPagesResponse = (gscControllerQueryPagesResponseSuccess | gscControllerQueryPagesResponseError)

export const getGscControllerQueryPagesUrl = (projectId: string,
    hash: string,
    params: GscControllerQueryPagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/gsc/queries/${hash}/pages?${stringifiedParams}` : `/api/v1/projects/${projectId}/gsc/queries/${hash}/pages`
}

/**
 * @summary Bir sorgunun sayfaları (`gsc_daily`); `hash` = `queryHash`.
 */
export const gscControllerQueryPages = async (projectId: string,
    hash: string,
    params: GscControllerQueryPagesParams, options?: Parameters<typeof customFetch>[1]): Promise<gscControllerQueryPagesResponse> => {

  return customFetch<gscControllerQueryPagesResponse>(getGscControllerQueryPagesUrl(projectId,hash,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGscControllerQueryPagesQueryKey = (projectId: string,
    hash: string,
    params?: GscControllerQueryPagesParams,) => {
    return [
    `/api/v1/projects/${projectId}/gsc/queries/${hash}/pages`, ...(params ? [params] : [])
    ] as const;
    }


export const getGscControllerQueryPagesQueryOptions = <TData = Awaited<ReturnType<typeof gscControllerQueryPages>>, TError = void>(projectId: string,
    hash: string,
    params: GscControllerQueryPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueryPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGscControllerQueryPagesQueryKey(projectId,hash,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof gscControllerQueryPages>>> = ({ signal }) => gscControllerQueryPages(projectId,hash,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && hash !== null && hash !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueryPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GscControllerQueryPagesQueryResult = NonNullable<Awaited<ReturnType<typeof gscControllerQueryPages>>>
export type GscControllerQueryPagesQueryError = void


export function useGscControllerQueryPages<TData = Awaited<ReturnType<typeof gscControllerQueryPages>>, TError = void>(
 projectId: string,
    hash: string,
    params: GscControllerQueryPagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueryPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerQueryPages>>,
          TError,
          Awaited<ReturnType<typeof gscControllerQueryPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerQueryPages<TData = Awaited<ReturnType<typeof gscControllerQueryPages>>, TError = void>(
 projectId: string,
    hash: string,
    params: GscControllerQueryPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueryPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerQueryPages>>,
          TError,
          Awaited<ReturnType<typeof gscControllerQueryPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerQueryPages<TData = Awaited<ReturnType<typeof gscControllerQueryPages>>, TError = void>(
 projectId: string,
    hash: string,
    params: GscControllerQueryPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueryPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Bir sorgunun sayfaları (`gsc_daily`); `hash` = `queryHash`.
 */

export function useGscControllerQueryPages<TData = Awaited<ReturnType<typeof gscControllerQueryPages>>, TError = void>(
 projectId: string,
    hash: string,
    params: GscControllerQueryPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerQueryPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGscControllerQueryPagesQueryOptions(projectId,hash,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type gscControllerPageQueriesResponse200 = {
  data: GscQueryListResponseDto
  status: 200
}

export type gscControllerPageQueriesResponse400 = {
  data: void
  status: 400
}

export type gscControllerPageQueriesResponse403 = {
  data: void
  status: 403
}

export type gscControllerPageQueriesResponse404 = {
  data: void
  status: 404
}

export type gscControllerPageQueriesResponseSuccess = (gscControllerPageQueriesResponse200) & {
  headers: Headers;
};
export type gscControllerPageQueriesResponseError = (gscControllerPageQueriesResponse400 | gscControllerPageQueriesResponse403 | gscControllerPageQueriesResponse404) & {
  headers: Headers;
};

export type gscControllerPageQueriesResponse = (gscControllerPageQueriesResponseSuccess | gscControllerPageQueriesResponseError)

export const getGscControllerPageQueriesUrl = (projectId: string,
    hash: string,
    params: GscControllerPageQueriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/gsc/pages/${hash}/queries?${stringifiedParams}` : `/api/v1/projects/${projectId}/gsc/pages/${hash}/queries`
}

/**
 * @summary Bir sayfanın sorguları (`gsc_daily`); `hash` = `pageHash`.
 */
export const gscControllerPageQueries = async (projectId: string,
    hash: string,
    params: GscControllerPageQueriesParams, options?: Parameters<typeof customFetch>[1]): Promise<gscControllerPageQueriesResponse> => {

  return customFetch<gscControllerPageQueriesResponse>(getGscControllerPageQueriesUrl(projectId,hash,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGscControllerPageQueriesQueryKey = (projectId: string,
    hash: string,
    params?: GscControllerPageQueriesParams,) => {
    return [
    `/api/v1/projects/${projectId}/gsc/pages/${hash}/queries`, ...(params ? [params] : [])
    ] as const;
    }


export const getGscControllerPageQueriesQueryOptions = <TData = Awaited<ReturnType<typeof gscControllerPageQueries>>, TError = void>(projectId: string,
    hash: string,
    params: GscControllerPageQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPageQueries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGscControllerPageQueriesQueryKey(projectId,hash,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof gscControllerPageQueries>>> = ({ signal }) => gscControllerPageQueries(projectId,hash,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && hash !== null && hash !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof gscControllerPageQueries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GscControllerPageQueriesQueryResult = NonNullable<Awaited<ReturnType<typeof gscControllerPageQueries>>>
export type GscControllerPageQueriesQueryError = void


export function useGscControllerPageQueries<TData = Awaited<ReturnType<typeof gscControllerPageQueries>>, TError = void>(
 projectId: string,
    hash: string,
    params: GscControllerPageQueriesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPageQueries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerPageQueries>>,
          TError,
          Awaited<ReturnType<typeof gscControllerPageQueries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerPageQueries<TData = Awaited<ReturnType<typeof gscControllerPageQueries>>, TError = void>(
 projectId: string,
    hash: string,
    params: GscControllerPageQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPageQueries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof gscControllerPageQueries>>,
          TError,
          Awaited<ReturnType<typeof gscControllerPageQueries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGscControllerPageQueries<TData = Awaited<ReturnType<typeof gscControllerPageQueries>>, TError = void>(
 projectId: string,
    hash: string,
    params: GscControllerPageQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPageQueries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Bir sayfanın sorguları (`gsc_daily`); `hash` = `pageHash`.
 */

export function useGscControllerPageQueries<TData = Awaited<ReturnType<typeof gscControllerPageQueries>>, TError = void>(
 projectId: string,
    hash: string,
    params: GscControllerPageQueriesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof gscControllerPageQueries>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGscControllerPageQueriesQueryOptions(projectId,hash,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






