/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateReportDto,
  CreateReportResponseDto,
  CreateReportScheduleDto,
  ReportDataResponseDto,
  ReportListResponseDto,
  ReportResponseDto,
  ReportScheduleListResponseDto,
  ReportScheduleResponseDto,
  ReportsControllerListParams,
  UpdateReportScheduleDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type reportsControllerListResponse200 = {
  data: ReportListResponseDto
  status: 200
}

export type reportsControllerListResponse403 = {
  data: void
  status: 403
}

export type reportsControllerListResponse404 = {
  data: void
  status: 404
}

export type reportsControllerListResponseSuccess = (reportsControllerListResponse200) & {
  headers: Headers;
};
export type reportsControllerListResponseError = (reportsControllerListResponse403 | reportsControllerListResponse404) & {
  headers: Headers;
};

export type reportsControllerListResponse = (reportsControllerListResponseSuccess | reportsControllerListResponseError)

export const getReportsControllerListUrl = (projectId: string,
    params: ReportsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/reports?${stringifiedParams}` : `/api/v1/projects/${projectId}/reports`
}

export const reportsControllerList = async (projectId: string,
    params: ReportsControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<reportsControllerListResponse> => {

  return customFetch<reportsControllerListResponse>(getReportsControllerListUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReportsControllerListQueryKey = (projectId: string,
    params?: ReportsControllerListParams,) => {
    return [
    `/api/v1/projects/${projectId}/reports`, ...(params ? [params] : [])
    ] as const;
    }


export const getReportsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerList>>, TError = void>(projectId: string,
    params: ReportsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerListQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerList>>> = ({ signal }) => reportsControllerList(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerList>>>
export type ReportsControllerListQueryError = void


export function useReportsControllerList<TData = Awaited<ReturnType<typeof reportsControllerList>>, TError = void>(
 projectId: string,
    params: ReportsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerList>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerList<TData = Awaited<ReturnType<typeof reportsControllerList>>, TError = void>(
 projectId: string,
    params: ReportsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerList>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerList<TData = Awaited<ReturnType<typeof reportsControllerList>>, TError = void>(
 projectId: string,
    params: ReportsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReportsControllerList<TData = Awaited<ReturnType<typeof reportsControllerList>>, TError = void>(
 projectId: string,
    params: ReportsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerListQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type reportsControllerCreateResponse201 = {
  data: CreateReportResponseDto
  status: 201
}

export type reportsControllerCreateResponse403 = {
  data: void
  status: 403
}

export type reportsControllerCreateResponse404 = {
  data: void
  status: 404
}

export type reportsControllerCreateResponseSuccess = (reportsControllerCreateResponse201) & {
  headers: Headers;
};
export type reportsControllerCreateResponseError = (reportsControllerCreateResponse403 | reportsControllerCreateResponse404) & {
  headers: Headers;
};

export type reportsControllerCreateResponse = (reportsControllerCreateResponseSuccess | reportsControllerCreateResponseError)

export const getReportsControllerCreateUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/reports`
}

export const reportsControllerCreate = async (projectId: string,
    createReportDto: CreateReportDto, options?: Parameters<typeof customFetch>[1]): Promise<reportsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<reportsControllerCreateResponse>(getReportsControllerCreateUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createReportDto)
  }
);}





export const getReportsControllerCreateMutationKey = () => ['reportsControllerCreate'] as const;

export const getReportsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportsControllerCreate>>, TError,ReportsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reportsControllerCreate>>, TError,ReportsControllerCreateMutationVariables, TContext> => {

const mutationKey = getReportsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportsControllerCreate>>, ReportsControllerCreateMutationVariables> = (props) => {
          const {projectId,data} = props ?? {};

          return  reportsControllerCreate(projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReportsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof reportsControllerCreate>>>
    export type ReportsControllerCreateMutationBody = CreateReportDto
    export type ReportsControllerCreateMutationError = void
    export type ReportsControllerCreateMutationVariables = {projectId: string;data: CreateReportDto}

    export const useReportsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportsControllerCreate>>, TError,ReportsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reportsControllerCreate>>,
        TError,
        ReportsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getReportsControllerCreateMutationOptions(options), queryClient);
    }
    export type reportsControllerFindOneResponse200 = {
  data: ReportResponseDto
  status: 200
}

export type reportsControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type reportsControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type reportsControllerFindOneResponseSuccess = (reportsControllerFindOneResponse200) & {
  headers: Headers;
};
export type reportsControllerFindOneResponseError = (reportsControllerFindOneResponse403 | reportsControllerFindOneResponse404) & {
  headers: Headers;
};

export type reportsControllerFindOneResponse = (reportsControllerFindOneResponseSuccess | reportsControllerFindOneResponseError)

export const getReportsControllerFindOneUrl = (projectId: string,
    reportId: string,) => {




  return `/api/v1/projects/${projectId}/reports/${reportId}`
}

export const reportsControllerFindOne = async (projectId: string,
    reportId: string, options?: Parameters<typeof customFetch>[1]): Promise<reportsControllerFindOneResponse> => {

  return customFetch<reportsControllerFindOneResponse>(getReportsControllerFindOneUrl(projectId,reportId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReportsControllerFindOneQueryKey = (projectId: string,
    reportId: string,) => {
    return [
    `/api/v1/projects/${projectId}/reports/${reportId}`
    ] as const;
    }


export const getReportsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerFindOne>>, TError = void>(projectId: string,
    reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerFindOneQueryKey(projectId,reportId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerFindOne>>> = ({ signal }) => reportsControllerFindOne(projectId,reportId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && reportId !== null && reportId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerFindOne>>>
export type ReportsControllerFindOneQueryError = void


export function useReportsControllerFindOne<TData = Awaited<ReturnType<typeof reportsControllerFindOne>>, TError = void>(
 projectId: string,
    reportId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerFindOne<TData = Awaited<ReturnType<typeof reportsControllerFindOne>>, TError = void>(
 projectId: string,
    reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerFindOne<TData = Awaited<ReturnType<typeof reportsControllerFindOne>>, TError = void>(
 projectId: string,
    reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReportsControllerFindOne<TData = Awaited<ReturnType<typeof reportsControllerFindOne>>, TError = void>(
 projectId: string,
    reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerFindOneQueryOptions(projectId,reportId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type reportsControllerDownloadResponse200 = {
  data: void
  status: 200
}

export type reportsControllerDownloadResponse403 = {
  data: void
  status: 403
}

export type reportsControllerDownloadResponse404 = {
  data: void
  status: 404
}

export type reportsControllerDownloadResponseSuccess = (reportsControllerDownloadResponse200) & {
  headers: Headers;
};
export type reportsControllerDownloadResponseError = (reportsControllerDownloadResponse403 | reportsControllerDownloadResponse404) & {
  headers: Headers;
};

export type reportsControllerDownloadResponse = (reportsControllerDownloadResponseSuccess | reportsControllerDownloadResponseError)

export const getReportsControllerDownloadUrl = (projectId: string,
    reportId: string,) => {




  return `/api/v1/projects/${projectId}/reports/${reportId}/download`
}

export const reportsControllerDownload = async (projectId: string,
    reportId: string, options?: Parameters<typeof customFetch>[1]): Promise<reportsControllerDownloadResponse> => {

  return customFetch<reportsControllerDownloadResponse>(getReportsControllerDownloadUrl(projectId,reportId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReportsControllerDownloadQueryKey = (projectId: string,
    reportId: string,) => {
    return [
    `/api/v1/projects/${projectId}/reports/${reportId}/download`
    ] as const;
    }


export const getReportsControllerDownloadQueryOptions = <TData = Awaited<ReturnType<typeof reportsControllerDownload>>, TError = void>(projectId: string,
    reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownload>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportsControllerDownloadQueryKey(projectId,reportId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportsControllerDownload>>> = ({ signal }) => reportsControllerDownload(projectId,reportId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && reportId !== null && reportId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownload>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportsControllerDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof reportsControllerDownload>>>
export type ReportsControllerDownloadQueryError = void


export function useReportsControllerDownload<TData = Awaited<ReturnType<typeof reportsControllerDownload>>, TError = void>(
 projectId: string,
    reportId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownload>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerDownload>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerDownload<TData = Awaited<ReturnType<typeof reportsControllerDownload>>, TError = void>(
 projectId: string,
    reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownload>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportsControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof reportsControllerDownload>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportsControllerDownload<TData = Awaited<ReturnType<typeof reportsControllerDownload>>, TError = void>(
 projectId: string,
    reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownload>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReportsControllerDownload<TData = Awaited<ReturnType<typeof reportsControllerDownload>>, TError = void>(
 projectId: string,
    reportId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportsControllerDownload>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportsControllerDownloadQueryOptions(projectId,reportId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type reportSchedulesControllerListResponse200 = {
  data: ReportScheduleListResponseDto
  status: 200
}

export type reportSchedulesControllerListResponse403 = {
  data: void
  status: 403
}

export type reportSchedulesControllerListResponse404 = {
  data: void
  status: 404
}

export type reportSchedulesControllerListResponseSuccess = (reportSchedulesControllerListResponse200) & {
  headers: Headers;
};
export type reportSchedulesControllerListResponseError = (reportSchedulesControllerListResponse403 | reportSchedulesControllerListResponse404) & {
  headers: Headers;
};

export type reportSchedulesControllerListResponse = (reportSchedulesControllerListResponseSuccess | reportSchedulesControllerListResponseError)

export const getReportSchedulesControllerListUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/report-schedules`
}

export const reportSchedulesControllerList = async (projectId: string, options?: Parameters<typeof customFetch>[1]): Promise<reportSchedulesControllerListResponse> => {

  return customFetch<reportSchedulesControllerListResponse>(getReportSchedulesControllerListUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReportSchedulesControllerListQueryKey = (projectId: string,) => {
    return [
    `/api/v1/projects/${projectId}/report-schedules`
    ] as const;
    }


export const getReportSchedulesControllerListQueryOptions = <TData = Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError = void>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportSchedulesControllerListQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportSchedulesControllerList>>> = ({ signal }) => reportSchedulesControllerList(projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportSchedulesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof reportSchedulesControllerList>>>
export type ReportSchedulesControllerListQueryError = void


export function useReportSchedulesControllerList<TData = Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError = void>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportSchedulesControllerList>>,
          TError,
          Awaited<ReturnType<typeof reportSchedulesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportSchedulesControllerList<TData = Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportSchedulesControllerList>>,
          TError,
          Awaited<ReturnType<typeof reportSchedulesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportSchedulesControllerList<TData = Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReportSchedulesControllerList<TData = Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportSchedulesControllerListQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type reportSchedulesControllerCreateResponse201 = {
  data: ReportScheduleResponseDto
  status: 201
}

export type reportSchedulesControllerCreateResponse403 = {
  data: void
  status: 403
}

export type reportSchedulesControllerCreateResponse404 = {
  data: void
  status: 404
}

export type reportSchedulesControllerCreateResponseSuccess = (reportSchedulesControllerCreateResponse201) & {
  headers: Headers;
};
export type reportSchedulesControllerCreateResponseError = (reportSchedulesControllerCreateResponse403 | reportSchedulesControllerCreateResponse404) & {
  headers: Headers;
};

export type reportSchedulesControllerCreateResponse = (reportSchedulesControllerCreateResponseSuccess | reportSchedulesControllerCreateResponseError)

export const getReportSchedulesControllerCreateUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/report-schedules`
}

export const reportSchedulesControllerCreate = async (projectId: string,
    createReportScheduleDto: CreateReportScheduleDto, options?: Parameters<typeof customFetch>[1]): Promise<reportSchedulesControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<reportSchedulesControllerCreateResponse>(getReportSchedulesControllerCreateUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createReportScheduleDto)
  }
);}





export const getReportSchedulesControllerCreateMutationKey = () => ['reportSchedulesControllerCreate'] as const;

export const getReportSchedulesControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerCreate>>, TError,ReportSchedulesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerCreate>>, TError,ReportSchedulesControllerCreateMutationVariables, TContext> => {

const mutationKey = getReportSchedulesControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportSchedulesControllerCreate>>, ReportSchedulesControllerCreateMutationVariables> = (props) => {
          const {projectId,data} = props ?? {};

          return  reportSchedulesControllerCreate(projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReportSchedulesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof reportSchedulesControllerCreate>>>
    export type ReportSchedulesControllerCreateMutationBody = CreateReportScheduleDto
    export type ReportSchedulesControllerCreateMutationError = void
    export type ReportSchedulesControllerCreateMutationVariables = {projectId: string;data: CreateReportScheduleDto}

    export const useReportSchedulesControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerCreate>>, TError,ReportSchedulesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reportSchedulesControllerCreate>>,
        TError,
        ReportSchedulesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getReportSchedulesControllerCreateMutationOptions(options), queryClient);
    }
    export type reportSchedulesControllerFindOneResponse200 = {
  data: ReportScheduleResponseDto
  status: 200
}

export type reportSchedulesControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type reportSchedulesControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type reportSchedulesControllerFindOneResponseSuccess = (reportSchedulesControllerFindOneResponse200) & {
  headers: Headers;
};
export type reportSchedulesControllerFindOneResponseError = (reportSchedulesControllerFindOneResponse403 | reportSchedulesControllerFindOneResponse404) & {
  headers: Headers;
};

export type reportSchedulesControllerFindOneResponse = (reportSchedulesControllerFindOneResponseSuccess | reportSchedulesControllerFindOneResponseError)

export const getReportSchedulesControllerFindOneUrl = (projectId: string,
    scheduleId: string,) => {




  return `/api/v1/projects/${projectId}/report-schedules/${scheduleId}`
}

export const reportSchedulesControllerFindOne = async (projectId: string,
    scheduleId: string, options?: Parameters<typeof customFetch>[1]): Promise<reportSchedulesControllerFindOneResponse> => {

  return customFetch<reportSchedulesControllerFindOneResponse>(getReportSchedulesControllerFindOneUrl(projectId,scheduleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReportSchedulesControllerFindOneQueryKey = (projectId: string,
    scheduleId: string,) => {
    return [
    `/api/v1/projects/${projectId}/report-schedules/${scheduleId}`
    ] as const;
    }


export const getReportSchedulesControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError = void>(projectId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportSchedulesControllerFindOneQueryKey(projectId,scheduleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>> = ({ signal }) => reportSchedulesControllerFindOne(projectId,scheduleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && scheduleId !== null && scheduleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportSchedulesControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>>
export type ReportSchedulesControllerFindOneQueryError = void


export function useReportSchedulesControllerFindOne<TData = Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError = void>(
 projectId: string,
    scheduleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportSchedulesControllerFindOne<TData = Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError = void>(
 projectId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportSchedulesControllerFindOne<TData = Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError = void>(
 projectId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReportSchedulesControllerFindOne<TData = Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError = void>(
 projectId: string,
    scheduleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportSchedulesControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportSchedulesControllerFindOneQueryOptions(projectId,scheduleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type reportSchedulesControllerUpdateResponse200 = {
  data: ReportScheduleResponseDto
  status: 200
}

export type reportSchedulesControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type reportSchedulesControllerUpdateResponse404 = {
  data: void
  status: 404
}

export type reportSchedulesControllerUpdateResponseSuccess = (reportSchedulesControllerUpdateResponse200) & {
  headers: Headers;
};
export type reportSchedulesControllerUpdateResponseError = (reportSchedulesControllerUpdateResponse403 | reportSchedulesControllerUpdateResponse404) & {
  headers: Headers;
};

export type reportSchedulesControllerUpdateResponse = (reportSchedulesControllerUpdateResponseSuccess | reportSchedulesControllerUpdateResponseError)

export const getReportSchedulesControllerUpdateUrl = (projectId: string,
    scheduleId: string,) => {




  return `/api/v1/projects/${projectId}/report-schedules/${scheduleId}`
}

export const reportSchedulesControllerUpdate = async (projectId: string,
    scheduleId: string,
    updateReportScheduleDto: UpdateReportScheduleDto, options?: Parameters<typeof customFetch>[1]): Promise<reportSchedulesControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<reportSchedulesControllerUpdateResponse>(getReportSchedulesControllerUpdateUrl(projectId,scheduleId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateReportScheduleDto)
  }
);}





export const getReportSchedulesControllerUpdateMutationKey = () => ['reportSchedulesControllerUpdate'] as const;

export const getReportSchedulesControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerUpdate>>, TError,ReportSchedulesControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerUpdate>>, TError,ReportSchedulesControllerUpdateMutationVariables, TContext> => {

const mutationKey = getReportSchedulesControllerUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportSchedulesControllerUpdate>>, ReportSchedulesControllerUpdateMutationVariables> = (props) => {
          const {projectId,scheduleId,data} = props ?? {};

          return  reportSchedulesControllerUpdate(projectId,scheduleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReportSchedulesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof reportSchedulesControllerUpdate>>>
    export type ReportSchedulesControllerUpdateMutationBody = UpdateReportScheduleDto
    export type ReportSchedulesControllerUpdateMutationError = void
    export type ReportSchedulesControllerUpdateMutationVariables = {projectId: string;scheduleId: string;data: UpdateReportScheduleDto}

    export const useReportSchedulesControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerUpdate>>, TError,ReportSchedulesControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reportSchedulesControllerUpdate>>,
        TError,
        ReportSchedulesControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getReportSchedulesControllerUpdateMutationOptions(options), queryClient);
    }
    export type reportSchedulesControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type reportSchedulesControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type reportSchedulesControllerDeleteResponse404 = {
  data: void
  status: 404
}

export type reportSchedulesControllerDeleteResponseSuccess = (reportSchedulesControllerDeleteResponse204) & {
  headers: Headers;
};
export type reportSchedulesControllerDeleteResponseError = (reportSchedulesControllerDeleteResponse403 | reportSchedulesControllerDeleteResponse404) & {
  headers: Headers;
};

export type reportSchedulesControllerDeleteResponse = (reportSchedulesControllerDeleteResponseSuccess | reportSchedulesControllerDeleteResponseError)

export const getReportSchedulesControllerDeleteUrl = (projectId: string,
    scheduleId: string,) => {




  return `/api/v1/projects/${projectId}/report-schedules/${scheduleId}`
}

export const reportSchedulesControllerDelete = async (projectId: string,
    scheduleId: string, options?: Parameters<typeof customFetch>[1]): Promise<reportSchedulesControllerDeleteResponse> => {

  return customFetch<reportSchedulesControllerDeleteResponse>(getReportSchedulesControllerDeleteUrl(projectId,scheduleId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getReportSchedulesControllerDeleteMutationKey = () => ['reportSchedulesControllerDelete'] as const;

export const getReportSchedulesControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerDelete>>, TError,ReportSchedulesControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerDelete>>, TError,ReportSchedulesControllerDeleteMutationVariables, TContext> => {

const mutationKey = getReportSchedulesControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportSchedulesControllerDelete>>, ReportSchedulesControllerDeleteMutationVariables> = (props) => {
          const {projectId,scheduleId} = props ?? {};

          return  reportSchedulesControllerDelete(projectId,scheduleId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ReportSchedulesControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof reportSchedulesControllerDelete>>>

    export type ReportSchedulesControllerDeleteMutationError = void
    export type ReportSchedulesControllerDeleteMutationVariables = {projectId: string;scheduleId: string}

    export const useReportSchedulesControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportSchedulesControllerDelete>>, TError,ReportSchedulesControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof reportSchedulesControllerDelete>>,
        TError,
        ReportSchedulesControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getReportSchedulesControllerDeleteMutationOptions(options), queryClient);
    }
    export type reportDataControllerDataResponse200 = {
  data: ReportDataResponseDto
  status: 200
}

export type reportDataControllerDataResponse401 = {
  data: void
  status: 401
}

export type reportDataControllerDataResponseSuccess = (reportDataControllerDataResponse200) & {
  headers: Headers;
};
export type reportDataControllerDataResponseError = (reportDataControllerDataResponse401) & {
  headers: Headers;
};

export type reportDataControllerDataResponse = (reportDataControllerDataResponseSuccess | reportDataControllerDataResponseError)

export const getReportDataControllerDataUrl = (id: string,) => {




  return `/api/v1/reports/${id}/data`
}

export const reportDataControllerData = async (id: string, options?: Parameters<typeof customFetch>[1]): Promise<reportDataControllerDataResponse> => {

  return customFetch<reportDataControllerDataResponse>(getReportDataControllerDataUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getReportDataControllerDataQueryKey = (id: string,) => {
    return [
    `/api/v1/reports/${id}/data`
    ] as const;
    }


export const getReportDataControllerDataQueryOptions = <TData = Awaited<ReturnType<typeof reportDataControllerData>>, TError = void>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDataControllerData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportDataControllerDataQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportDataControllerData>>> = ({ signal }) => reportDataControllerData(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportDataControllerData>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ReportDataControllerDataQueryResult = NonNullable<Awaited<ReturnType<typeof reportDataControllerData>>>
export type ReportDataControllerDataQueryError = void


export function useReportDataControllerData<TData = Awaited<ReturnType<typeof reportDataControllerData>>, TError = void>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDataControllerData>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportDataControllerData>>,
          TError,
          Awaited<ReturnType<typeof reportDataControllerData>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportDataControllerData<TData = Awaited<ReturnType<typeof reportDataControllerData>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDataControllerData>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof reportDataControllerData>>,
          TError,
          Awaited<ReturnType<typeof reportDataControllerData>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useReportDataControllerData<TData = Awaited<ReturnType<typeof reportDataControllerData>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDataControllerData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useReportDataControllerData<TData = Awaited<ReturnType<typeof reportDataControllerData>>, TError = void>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof reportDataControllerData>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getReportDataControllerDataQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






