/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AuthResponseDto,
  LoginDto,
  RegisterDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type authControllerRegisterResponse201 = {
  data: AuthResponseDto
  status: 201
}

export type authControllerRegisterResponse403 = {
  data: void
  status: 403
}

export type authControllerRegisterResponse429 = {
  data: void
  status: 429
}

export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse201) & {
  headers: Headers;
};
export type authControllerRegisterResponseError = (authControllerRegisterResponse403 | authControllerRegisterResponse429) & {
  headers: Headers;
};

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess | authControllerRegisterResponseError)

export const getAuthControllerRegisterUrl = () => {




  return `/api/v1/auth/register`
}

/**
 * @summary Sadece hiç kullanıcı yokken ilk kullanıcıyı oluşturur ve oturum açar.
 */
export const authControllerRegister = async (registerDto: RegisterDto, options?: Parameters<typeof customFetch>[1]): Promise<authControllerRegisterResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<authControllerRegisterResponse>(getAuthControllerRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registerDto)
  }
);}





export const getAuthControllerRegisterMutationKey = () => ['authControllerRegister'] as const;

export const getAuthControllerRegisterMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,AuthControllerRegisterMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,AuthControllerRegisterMutationVariables, TContext> => {

const mutationKey = getAuthControllerRegisterMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegister>>, AuthControllerRegisterMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerRegister(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
    export type AuthControllerRegisterMutationBody = RegisterDto
    export type AuthControllerRegisterMutationError = void
    export type AuthControllerRegisterMutationVariables = {data: RegisterDto}

    /**
 * @summary Sadece hiç kullanıcı yokken ilk kullanıcıyı oluşturur ve oturum açar.
 */
export const useAuthControllerRegister = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,AuthControllerRegisterMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRegister>>,
        TError,
        AuthControllerRegisterMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerRegisterMutationOptions(options), queryClient);
    }
    export type authControllerLoginResponse200 = {
  data: AuthResponseDto
  status: 200
}

export type authControllerLoginResponse401 = {
  data: void
  status: 401
}

export type authControllerLoginResponse429 = {
  data: void
  status: 429
}

export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
export type authControllerLoginResponseError = (authControllerLoginResponse401 | authControllerLoginResponse429) & {
  headers: Headers;
};

export type authControllerLoginResponse = (authControllerLoginResponseSuccess | authControllerLoginResponseError)

export const getAuthControllerLoginUrl = () => {




  return `/api/v1/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: Parameters<typeof customFetch>[1]): Promise<authControllerLoginResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<authControllerLoginResponse>(getAuthControllerLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginDto)
  }
);}





export const getAuthControllerLoginMutationKey = () => ['authControllerLogin'] as const;

export const getAuthControllerLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,AuthControllerLoginMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,AuthControllerLoginMutationVariables, TContext> => {

const mutationKey = getAuthControllerLoginMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, AuthControllerLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  authControllerLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    export type AuthControllerLoginMutationBody = LoginDto
    export type AuthControllerLoginMutationError = void
    export type AuthControllerLoginMutationVariables = {data: LoginDto}

    export const useAuthControllerLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,AuthControllerLoginMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        AuthControllerLoginMutationVariables,
        TContext
      > => {
      return useMutation(getAuthControllerLoginMutationOptions(options), queryClient);
    }
    export type authControllerRefreshResponse200 = {
  data: AuthResponseDto
  status: 200
}

export type authControllerRefreshResponse401 = {
  data: void
  status: 401
}

export type authControllerRefreshResponse429 = {
  data: void
  status: 429
}

export type authControllerRefreshResponseSuccess = (authControllerRefreshResponse200) & {
  headers: Headers;
};
export type authControllerRefreshResponseError = (authControllerRefreshResponse401 | authControllerRefreshResponse429) & {
  headers: Headers;
};

export type authControllerRefreshResponse = (authControllerRefreshResponseSuccess | authControllerRefreshResponseError)

export const getAuthControllerRefreshUrl = () => {




  return `/api/v1/auth/refresh`
}

/**
 * @summary Refresh token cookie'den okunur, rotation uygulanır ve yeni cookie yazılır.
 */
export const authControllerRefresh = async ( options?: Parameters<typeof customFetch>[1]): Promise<authControllerRefreshResponse> => {

  return customFetch<authControllerRefreshResponse>(getAuthControllerRefreshUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAuthControllerRefreshMutationKey = () => ['authControllerRefresh'] as const;

export const getAuthControllerRefreshMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext> => {

const mutationKey = getAuthControllerRefreshMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefresh>>, void> = () => {


          return  authControllerRefresh(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefresh>>>

    export type AuthControllerRefreshMutationError = void


    /**
 * @summary Refresh token cookie'den okunur, rotation uygulanır ve yeni cookie yazılır.
 */
export const useAuthControllerRefresh = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRefresh>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerRefreshMutationOptions(options), queryClient);
    }
    export type authControllerLogoutResponse204 = {
  data: void
  status: 204
}

export type authControllerLogoutResponse429 = {
  data: void
  status: 429
}

export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse204) & {
  headers: Headers;
};
export type authControllerLogoutResponseError = (authControllerLogoutResponse429) & {
  headers: Headers;
};

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess | authControllerLogoutResponseError)

export const getAuthControllerLogoutUrl = () => {




  return `/api/v1/auth/logout`
}

/**
 * @summary Refresh token ailesini iptal eder ve cookie'yi siler.
 */
export const authControllerLogout = async ( options?: Parameters<typeof customFetch>[1]): Promise<authControllerLogoutResponse> => {

  return customFetch<authControllerLogoutResponse>(getAuthControllerLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getAuthControllerLogoutMutationKey = () => ['authControllerLogout'] as const;

export const getAuthControllerLogoutMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext> => {

const mutationKey = getAuthControllerLogoutMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {


          return  authControllerLogout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>

    export type AuthControllerLogoutMutationError = void


    /**
 * @summary Refresh token ailesini iptal eder ve cookie'yi siler.
 */
export const useAuthControllerLogout = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getAuthControllerLogoutMutationOptions(options), queryClient);
    }
