/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ProjectSummaryResponseDto,
  SummaryControllerForProjectParams
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type summaryControllerForProjectResponse200 = {
  data: ProjectSummaryResponseDto
  status: 200
}

export type summaryControllerForProjectResponse400 = {
  data: void
  status: 400
}

export type summaryControllerForProjectResponse403 = {
  data: void
  status: 403
}

export type summaryControllerForProjectResponse404 = {
  data: void
  status: 404
}

export type summaryControllerForProjectResponseSuccess = (summaryControllerForProjectResponse200) & {
  headers: Headers;
};
export type summaryControllerForProjectResponseError = (summaryControllerForProjectResponse400 | summaryControllerForProjectResponse403 | summaryControllerForProjectResponse404) & {
  headers: Headers;
};

export type summaryControllerForProjectResponse = (summaryControllerForProjectResponseSuccess | summaryControllerForProjectResponseError)

export const getSummaryControllerForProjectUrl = (projectId: string,
    params?: SummaryControllerForProjectParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/summary?${stringifiedParams}` : `/api/v1/projects/${projectId}/summary`
}

/**
 * @summary Günlük seri (`project_daily_summary`).
 */
export const summaryControllerForProject = async (projectId: string,
    params?: SummaryControllerForProjectParams, options?: Parameters<typeof customFetch>[1]): Promise<summaryControllerForProjectResponse> => {

  return customFetch<summaryControllerForProjectResponse>(getSummaryControllerForProjectUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSummaryControllerForProjectQueryKey = (projectId: string,
    params?: SummaryControllerForProjectParams,) => {
    return [
    `/api/v1/projects/${projectId}/summary`, ...(params ? [params] : [])
    ] as const;
    }


export const getSummaryControllerForProjectQueryOptions = <TData = Awaited<ReturnType<typeof summaryControllerForProject>>, TError = void>(projectId: string,
    params?: SummaryControllerForProjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof summaryControllerForProject>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSummaryControllerForProjectQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof summaryControllerForProject>>> = ({ signal }) => summaryControllerForProject(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof summaryControllerForProject>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SummaryControllerForProjectQueryResult = NonNullable<Awaited<ReturnType<typeof summaryControllerForProject>>>
export type SummaryControllerForProjectQueryError = void


export function useSummaryControllerForProject<TData = Awaited<ReturnType<typeof summaryControllerForProject>>, TError = void>(
 projectId: string,
    params: undefined |  SummaryControllerForProjectParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof summaryControllerForProject>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof summaryControllerForProject>>,
          TError,
          Awaited<ReturnType<typeof summaryControllerForProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSummaryControllerForProject<TData = Awaited<ReturnType<typeof summaryControllerForProject>>, TError = void>(
 projectId: string,
    params?: SummaryControllerForProjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof summaryControllerForProject>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof summaryControllerForProject>>,
          TError,
          Awaited<ReturnType<typeof summaryControllerForProject>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSummaryControllerForProject<TData = Awaited<ReturnType<typeof summaryControllerForProject>>, TError = void>(
 projectId: string,
    params?: SummaryControllerForProjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof summaryControllerForProject>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Günlük seri (`project_daily_summary`).
 */

export function useSummaryControllerForProject<TData = Awaited<ReturnType<typeof summaryControllerForProject>>, TError = void>(
 projectId: string,
    params?: SummaryControllerForProjectParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof summaryControllerForProject>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSummaryControllerForProjectQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






