/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClientListResponseDto,
  ClientResponseDto,
  ClientsControllerListParams,
  CreateClientDto,
  UpdateClientDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type clientsControllerListResponse200 = {
  data: ClientListResponseDto
  status: 200
}

export type clientsControllerListResponse403 = {
  data: void
  status: 403
}

export type clientsControllerListResponseSuccess = (clientsControllerListResponse200) & {
  headers: Headers;
};
export type clientsControllerListResponseError = (clientsControllerListResponse403) & {
  headers: Headers;
};

export type clientsControllerListResponse = (clientsControllerListResponseSuccess | clientsControllerListResponseError)

export const getClientsControllerListUrl = (params: ClientsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/clients?${stringifiedParams}` : `/api/v1/clients`
}

/**
 * @summary `client_viewer` yalnız kendi client'ını görür.
 */
export const clientsControllerList = async (params: ClientsControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<clientsControllerListResponse> => {

  return customFetch<clientsControllerListResponse>(getClientsControllerListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getClientsControllerListQueryKey = (params?: ClientsControllerListParams,) => {
    return [
    `/api/v1/clients`, ...(params ? [params] : [])
    ] as const;
    }


export const getClientsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = void>(params: ClientsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClientsControllerListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clientsControllerList>>> = ({ signal }) => clientsControllerList(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClientsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof clientsControllerList>>>
export type ClientsControllerListQueryError = void


export function useClientsControllerList<TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = void>(
 params: ClientsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsControllerList>>,
          TError,
          Awaited<ReturnType<typeof clientsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClientsControllerList<TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = void>(
 params: ClientsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsControllerList>>,
          TError,
          Awaited<ReturnType<typeof clientsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClientsControllerList<TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = void>(
 params: ClientsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary `client_viewer` yalnız kendi client'ını görür.
 */

export function useClientsControllerList<TData = Awaited<ReturnType<typeof clientsControllerList>>, TError = void>(
 params: ClientsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClientsControllerListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type clientsControllerCreateResponse201 = {
  data: ClientResponseDto
  status: 201
}

export type clientsControllerCreateResponse403 = {
  data: void
  status: 403
}

export type clientsControllerCreateResponseSuccess = (clientsControllerCreateResponse201) & {
  headers: Headers;
};
export type clientsControllerCreateResponseError = (clientsControllerCreateResponse403) & {
  headers: Headers;
};

export type clientsControllerCreateResponse = (clientsControllerCreateResponseSuccess | clientsControllerCreateResponseError)

export const getClientsControllerCreateUrl = () => {




  return `/api/v1/clients`
}

export const clientsControllerCreate = async (createClientDto: CreateClientDto, options?: Parameters<typeof customFetch>[1]): Promise<clientsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<clientsControllerCreateResponse>(getClientsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createClientDto)
  }
);}





export const getClientsControllerCreateMutationKey = () => ['clientsControllerCreate'] as const;

export const getClientsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerCreate>>, TError,ClientsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof clientsControllerCreate>>, TError,ClientsControllerCreateMutationVariables, TContext> => {

const mutationKey = getClientsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsControllerCreate>>, ClientsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  clientsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof clientsControllerCreate>>>
    export type ClientsControllerCreateMutationBody = CreateClientDto
    export type ClientsControllerCreateMutationError = void
    export type ClientsControllerCreateMutationVariables = {data: CreateClientDto}

    export const useClientsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerCreate>>, TError,ClientsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientsControllerCreate>>,
        TError,
        ClientsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getClientsControllerCreateMutationOptions(options), queryClient);
    }
    export type clientsControllerFindOneResponse200 = {
  data: ClientResponseDto
  status: 200
}

export type clientsControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type clientsControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type clientsControllerFindOneResponseSuccess = (clientsControllerFindOneResponse200) & {
  headers: Headers;
};
export type clientsControllerFindOneResponseError = (clientsControllerFindOneResponse403 | clientsControllerFindOneResponse404) & {
  headers: Headers;
};

export type clientsControllerFindOneResponse = (clientsControllerFindOneResponseSuccess | clientsControllerFindOneResponseError)

export const getClientsControllerFindOneUrl = (clientId: string,) => {




  return `/api/v1/clients/${clientId}`
}

export const clientsControllerFindOne = async (clientId: string, options?: Parameters<typeof customFetch>[1]): Promise<clientsControllerFindOneResponse> => {

  return customFetch<clientsControllerFindOneResponse>(getClientsControllerFindOneUrl(clientId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getClientsControllerFindOneQueryKey = (clientId: string,) => {
    return [
    `/api/v1/clients/${clientId}`
    ] as const;
    }


export const getClientsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof clientsControllerFindOne>>, TError = void>(clientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClientsControllerFindOneQueryKey(clientId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof clientsControllerFindOne>>> = ({ signal }) => clientsControllerFindOne(clientId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: clientId !== null && clientId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clientsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ClientsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof clientsControllerFindOne>>>
export type ClientsControllerFindOneQueryError = void


export function useClientsControllerFindOne<TData = Awaited<ReturnType<typeof clientsControllerFindOne>>, TError = void>(
 clientId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof clientsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClientsControllerFindOne<TData = Awaited<ReturnType<typeof clientsControllerFindOne>>, TError = void>(
 clientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof clientsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof clientsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useClientsControllerFindOne<TData = Awaited<ReturnType<typeof clientsControllerFindOne>>, TError = void>(
 clientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useClientsControllerFindOne<TData = Awaited<ReturnType<typeof clientsControllerFindOne>>, TError = void>(
 clientId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof clientsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getClientsControllerFindOneQueryOptions(clientId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type clientsControllerUpdateResponse200 = {
  data: ClientResponseDto
  status: 200
}

export type clientsControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type clientsControllerUpdateResponse404 = {
  data: void
  status: 404
}

export type clientsControllerUpdateResponseSuccess = (clientsControllerUpdateResponse200) & {
  headers: Headers;
};
export type clientsControllerUpdateResponseError = (clientsControllerUpdateResponse403 | clientsControllerUpdateResponse404) & {
  headers: Headers;
};

export type clientsControllerUpdateResponse = (clientsControllerUpdateResponseSuccess | clientsControllerUpdateResponseError)

export const getClientsControllerUpdateUrl = (clientId: string,) => {




  return `/api/v1/clients/${clientId}`
}

export const clientsControllerUpdate = async (clientId: string,
    updateClientDto: UpdateClientDto, options?: Parameters<typeof customFetch>[1]): Promise<clientsControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<clientsControllerUpdateResponse>(getClientsControllerUpdateUrl(clientId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateClientDto)
  }
);}





export const getClientsControllerUpdateMutationKey = () => ['clientsControllerUpdate'] as const;

export const getClientsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerUpdate>>, TError,ClientsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof clientsControllerUpdate>>, TError,ClientsControllerUpdateMutationVariables, TContext> => {

const mutationKey = getClientsControllerUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsControllerUpdate>>, ClientsControllerUpdateMutationVariables> = (props) => {
          const {clientId,data} = props ?? {};

          return  clientsControllerUpdate(clientId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof clientsControllerUpdate>>>
    export type ClientsControllerUpdateMutationBody = UpdateClientDto
    export type ClientsControllerUpdateMutationError = void
    export type ClientsControllerUpdateMutationVariables = {clientId: string;data: UpdateClientDto}

    export const useClientsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerUpdate>>, TError,ClientsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientsControllerUpdate>>,
        TError,
        ClientsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getClientsControllerUpdateMutationOptions(options), queryClient);
    }
    export type clientsControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type clientsControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type clientsControllerDeleteResponse404 = {
  data: void
  status: 404
}

export type clientsControllerDeleteResponseSuccess = (clientsControllerDeleteResponse204) & {
  headers: Headers;
};
export type clientsControllerDeleteResponseError = (clientsControllerDeleteResponse403 | clientsControllerDeleteResponse404) & {
  headers: Headers;
};

export type clientsControllerDeleteResponse = (clientsControllerDeleteResponseSuccess | clientsControllerDeleteResponseError)

export const getClientsControllerDeleteUrl = (clientId: string,) => {




  return `/api/v1/clients/${clientId}`
}

export const clientsControllerDelete = async (clientId: string, options?: Parameters<typeof customFetch>[1]): Promise<clientsControllerDeleteResponse> => {

  return customFetch<clientsControllerDeleteResponse>(getClientsControllerDeleteUrl(clientId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getClientsControllerDeleteMutationKey = () => ['clientsControllerDelete'] as const;

export const getClientsControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerDelete>>, TError,ClientsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof clientsControllerDelete>>, TError,ClientsControllerDeleteMutationVariables, TContext> => {

const mutationKey = getClientsControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientsControllerDelete>>, ClientsControllerDeleteMutationVariables> = (props) => {
          const {clientId} = props ?? {};

          return  clientsControllerDelete(clientId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClientsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof clientsControllerDelete>>>

    export type ClientsControllerDeleteMutationError = void
    export type ClientsControllerDeleteMutationVariables = {clientId: string}

    export const useClientsControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientsControllerDelete>>, TError,ClientsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clientsControllerDelete>>,
        TError,
        ClientsControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getClientsControllerDeleteMutationOptions(options), queryClient);
    }
