/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
export interface UserResponseDto {
  id: string;
  email: string;
  name: string;
  /** @nullable */
  lastLoginAt: string | null;
  createdAt: string;
}

export interface RegisterDto {
  /** @maxLength 254 */
  email: string;
  /** @maxLength 200 */
  name: string;
  /**
     * En az 8, en fazla 256 karakter.
     * @minLength 8
     * @maxLength 256
     */
  password: string;
}

export type AuthResponseDtoTokenType = typeof AuthResponseDtoTokenType[keyof typeof AuthResponseDtoTokenType];


export const AuthResponseDtoTokenType = {
  Bearer: 'Bearer',
} as const;

export interface AuthResponseDto {
  tokenType: AuthResponseDtoTokenType;
  accessToken: string;
  /** Access token ömrü, saniye. */
  expiresIn: number;
  user: UserResponseDto;
}

export interface RegisterInvitedDto {
  /**
     * Davet bağlantısındaki token.
     * @maxLength 256
     */
  token: string;
  /** @maxLength 200 */
  name: string;
  /**
     * En az 8, en fazla 256 karakter.
     * @minLength 8
     * @maxLength 256
     */
  password: string;
}

export interface LoginDto {
  /** @maxLength 254 */
  email: string;
  /** @maxLength 256 */
  password: string;
}

export interface ReportBrandingDto {
  /** @maxLength 2048 */
  logoUrl?: string;
  /**
     * `#1d4ed8` biçiminde.
     * @pattern ^#?([0-9A-F]{3}|[0-9A-F]{4}|[0-9A-F]{6}|[0-9A-F]{8})$
     */
  primaryColor?: string;
}

export interface OrganizationSettingsDto {
  /** IANA saat dilimi, ör. `Europe/Istanbul`. */
  timezone?: string;
  /**
     * Varsayılan dil kodu, ör. `tr`.
     * @minLength 2
     * @maxLength 10
     */
  defaultLanguage?: string;
  reportBranding?: ReportBrandingDto;
}

export interface CreateOrganizationDto {
  /** @maxLength 200 */
  name: string;
  /**
     * Küçük harf, rakam ve tire. Verilmezse addan üretilir.
     * @maxLength 60
     */
  slug?: string;
  settings?: OrganizationSettingsDto;
}

export type OrgRole = typeof OrgRole[keyof typeof OrgRole];


export const OrgRole = {
  owner: 'owner',
  admin: 'admin',
  analyst: 'analyst',
  client_viewer: 'client_viewer',
} as const;

export interface UserOrganizationResponseDto {
  role: OrgRole;
  id: string;
  name: string;
  slug: string;
  /**
     * client_viewer ise görebildiği client.
     * @nullable
     */
  clientId: string | null;
}

export interface UserOrganizationListResponseDto {
  items: UserOrganizationResponseDto[];
  total: number;
  page: number;
  limit: number;
}

export interface OrganizationResponseDto {
  id: string;
  name: string;
  slug: string;
  settings: OrganizationSettingsDto;
  createdAt: string;
  updatedAt: string;
}

export interface UpdateOrganizationDto {
  /** @maxLength 200 */
  name?: string;
  /** @maxLength 60 */
  slug?: string;
  /** Verilirse mevcut ayarların tamamının yerine geçer. */
  settings?: OrganizationSettingsDto;
}

export interface MemberResponseDto {
  role: OrgRole;
  userId: string;
  email: string;
  name: string;
  /** @nullable */
  clientId: string | null;
  /** Üyeliğin başladığı an. */
  joinedAt: string;
}

export interface MemberListResponseDto {
  items: MemberResponseDto[];
  total: number;
  page: number;
  limit: number;
}

export interface UpdateMemberRoleDto {
  role: OrgRole;
  /** client_viewer için zorunlu, diğer rollerde verilmez. */
  clientId?: string;
}

export interface MemberRoleResponseDto {
  role: OrgRole;
  userId: string;
  /** @nullable */
  clientId: string | null;
}

export interface CreateInvitationDto {
  role: OrgRole;
  /** @maxLength 254 */
  email: string;
  /** client_viewer için zorunlu, diğer rollerde verilmez. */
  clientId?: string;
}

export interface CreatedInvitationResponseDto {
  role: OrgRole;
  /** Mail gönderilemediyse false; davet geçerlidir, tekrar oluşturularak yeniden gönderilebilir. */
  emailSent: boolean;
  id: string;
  email: string;
  /** @nullable */
  clientId: string | null;
  expiresAt: string;
  /** @nullable */
  invitedBy: string | null;
  createdAt: string;
}

export interface InvitationResponseDto {
  role: OrgRole;
  id: string;
  email: string;
  /** @nullable */
  clientId: string | null;
  expiresAt: string;
  /** @nullable */
  invitedBy: string | null;
  createdAt: string;
}

export interface InvitationListResponseDto {
  items: InvitationResponseDto[];
  total: number;
  page: number;
  limit: number;
}

export interface InvitationTokenDto {
  /** @maxLength 256 */
  token: string;
}

export interface InvitationPreviewResponseDto {
  role: OrgRole;
  organizationName: string;
  email: string;
  expiresAt: string;
  /** true ise kullanıcı giriş yapıp kabul eder; false ise ad ve şifreyle kayıt olur. */
  userExists: boolean;
}

export interface AcceptInvitationResponseDto {
  role: OrgRole;
  organizationId: string;
  /** @nullable */
  clientId: string | null;
}

export type ClientResponseDtoBranding = { [key: string]: unknown };

export interface ClientResponseDto {
  id: string;
  name: string;
  contactEmails: string[];
  /** @nullable */
  notes: string | null;
  branding: ClientResponseDtoBranding;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface ClientListResponseDto {
  items: ClientResponseDto[];
  total: number;
  page: number;
  limit: number;
}

export type CreateClientDtoBranding = { [key: string]: unknown };

export interface CreateClientDto {
  /** @maxLength 200 */
  name: string;
  /** @maxItems 20 */
  contactEmails?: string[];
  /** @maxLength 5000 */
  notes?: string;
  branding?: CreateClientDtoBranding;
  isActive?: boolean;
}

export type UpdateClientDtoBranding = { [key: string]: unknown };

export interface UpdateClientDto {
  /** @maxLength 200 */
  name?: string;
  /** @maxItems 20 */
  contactEmails?: string[];
  /** @maxLength 5000 */
  notes?: string;
  branding?: UpdateClientDtoBranding;
  isActive?: boolean;
}

export type ProjectStatus = typeof ProjectStatus[keyof typeof ProjectStatus];


export const ProjectStatus = {
  active: 'active',
  paused: 'paused',
  archived: 'archived',
} as const;

export interface ProjectResponseDto {
  status: ProjectStatus;
  id: string;
  clientId: string;
  name: string;
  domain: string;
  /** @nullable */
  countryCode: string | null;
  /** @nullable */
  languageCode: string | null;
  /** @nullable */
  dfsLocationCode: number | null;
  /** @nullable */
  dfsLanguageCode: string | null;
  /** @nullable */
  timezone: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ProjectListResponseDto {
  items: ProjectResponseDto[];
  total: number;
  page: number;
  limit: number;
}

export type CreateProjectDtoStatus = typeof CreateProjectDtoStatus[keyof typeof CreateProjectDtoStatus];


export const CreateProjectDtoStatus = {
  active: 'active',
  paused: 'paused',
  archived: 'archived',
} as const;

export interface CreateProjectDto {
  clientId: string;
  /** @maxLength 200 */
  name: string;
  /**
     * Normalize edilir (protokol, www, path ve sondaki slash atılır).
     * @maxLength 255
     */
  domain: string;
  /** @maxLength 2 */
  countryCode?: string;
  /** @maxLength 10 */
  languageCode?: string;
  dfsLocationCode?: number;
  /** @maxLength 10 */
  dfsLanguageCode?: string;
  /** @maxLength 100 */
  timezone?: string;
  status?: CreateProjectDtoStatus;
}

export type UpdateProjectDtoStatus = typeof UpdateProjectDtoStatus[keyof typeof UpdateProjectDtoStatus];


export const UpdateProjectDtoStatus = {
  active: 'active',
  paused: 'paused',
  archived: 'archived',
} as const;

export interface UpdateProjectDto {
  clientId?: string;
  /** @maxLength 200 */
  name?: string;
  /**
     * Normalize edilir (protokol, www, path ve sondaki slash atılır).
     * @maxLength 255
     */
  domain?: string;
  /** @maxLength 2 */
  countryCode?: string;
  /** @maxLength 10 */
  languageCode?: string;
  dfsLocationCode?: number;
  /** @maxLength 10 */
  dfsLanguageCode?: string;
  /** @maxLength 100 */
  timezone?: string;
  status?: UpdateProjectDtoStatus;
}

export type ConnectionType = typeof ConnectionType[keyof typeof ConnectionType];


export const ConnectionType = {
  gsc: 'gsc',
  ga4: 'ga4',
} as const;

export type ConnectionAuthType = typeof ConnectionAuthType[keyof typeof ConnectionAuthType];


export const ConnectionAuthType = {
  service_account: 'service_account',
  oauth: 'oauth',
} as const;

export type ConnectionStatus = typeof ConnectionStatus[keyof typeof ConnectionStatus];


export const ConnectionStatus = {
  pending: 'pending',
  active: 'active',
  error: 'error',
  revoked: 'revoked',
} as const;

export type ConnectionBackfillStatus = typeof ConnectionBackfillStatus[keyof typeof ConnectionBackfillStatus];


export const ConnectionBackfillStatus = {
  pending: 'pending',
  running: 'running',
  done: 'done',
  failed: 'failed',
} as const;

export type ConnectionResponseDtoBackfillProgress = { [key: string]: unknown };

export interface ConnectionResponseDto {
  type: ConnectionType;
  authType: ConnectionAuthType;
  status: ConnectionStatus;
  backfillStatus: ConnectionBackfillStatus;
  id: string;
  projectId: string;
  externalId: string;
  /** @nullable */
  lastVerifiedAt: string | null;
  /** @nullable */
  lastSyncedAt: string | null;
  /** @nullable */
  lastError: string | null;
  backfillProgress: ConnectionResponseDtoBackfillProgress;
  createdAt: string;
  updatedAt: string;
}

export interface ConnectionListResponseDto {
  items: ConnectionResponseDto[];
}

export type CreateConnectionDtoType = typeof CreateConnectionDtoType[keyof typeof CreateConnectionDtoType];


export const CreateConnectionDtoType = {
  gsc: 'gsc',
  ga4: 'ga4',
} as const;

export interface CreateConnectionDto {
  type: CreateConnectionDtoType;
  /**
     * GSC: `sc-domain:example.com` ya da `https://example.com/`. GA4: `properties/123456789`.
     * @maxLength 255
     */
  externalId: string;
}

export interface GscSiteResponseDto {
  siteUrl: string;
  permissionLevel: string;
}

export interface GscSiteListResponseDto {
  items: GscSiteResponseDto[];
}

export interface ServiceAccountResponseDto {
  email: string;
}

export type UsageGroupBy = typeof UsageGroupBy[keyof typeof UsageGroupBy];


export const UsageGroupBy = {
  project: 'project',
  provider: 'provider',
  day: 'day',
} as const;

export interface UsageReportRowDto {
  /** `groupBy`'a göre: `project_id`, `provider` ya da `YYYY-MM-DD`. */
  key: string;
  cost: number;
  units: number;
}

export interface UsageReportResponseDto {
  from: string;
  to: string;
  groupBy: UsageGroupBy;
  items: UsageReportRowDto[];
  totalCost: number;
  totalUnits: number;
}

export interface GscSyncResponseDto {
  /** `job_runs` kaydının id'si; durum bu kayıttan izlenir. */
  runId: string;
}

export type GscCompareMode = typeof GscCompareMode[keyof typeof GscCompareMode];


export const GscCompareMode = {
  previous: 'previous',
  year: 'year',
} as const;

export interface GscTotalsDto {
  clicks: number;
  impressions: number;
  /** clicks / impressions (0-1). */
  ctr: number;
  /** Gösterimle ağırlıklı ortalama pozisyon. */
  position: number;
}

export interface GscDailyPointDto {
  date: string;
  clicks: number;
  impressions: number;
  /** clicks / impressions (0-1). */
  ctr: number;
  /** Gösterimle ağırlıklı ortalama pozisyon. */
  position: number;
}

export interface GscPeriodDto {
  from: string;
  to: string;
  totals: GscTotalsDto;
  series: GscDailyPointDto[];
}

export interface GscOverviewResponseDto {
  from: string;
  to: string;
  /** @nullable */
  compare: GscPeriodDto | null;
  totals: GscTotalsDto;
  series: GscDailyPointDto[];
}

export type GscSortField = typeof GscSortField[keyof typeof GscSortField];


export const GscSortField = {
  clicks: 'clicks',
  impressions: 'impressions',
  ctr: 'ctr',
  position: 'position',
} as const;

export type SortOrder = typeof SortOrder[keyof typeof SortOrder];


export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export interface GscQueryRowDto {
  clicks: number;
  impressions: number;
  /** clicks / impressions (0-1). */
  ctr: number;
  /** Gösterimle ağırlıklı ortalama pozisyon. */
  position: number;
  /** `md5(query)`; `queries/:hash/pages` için. */
  queryHash: string;
  query: string;
}

export interface GscQueryListResponseDto {
  items: GscQueryRowDto[];
  total: number;
  page: number;
  limit: number;
}

export interface GscPageRowDto {
  clicks: number;
  impressions: number;
  /** clicks / impressions (0-1). */
  ctr: number;
  /** Gösterimle ağırlıklı ortalama pozisyon. */
  position: number;
  /** `md5(page)`; `pages/:hash/queries` için. */
  pageHash: string;
  page: string;
}

export interface GscPageListResponseDto {
  items: GscPageRowDto[];
  total: number;
  page: number;
  limit: number;
}

export interface Ga4SyncResponseDto {
  /** `job_runs` kaydının id'si; durum bu kayıttan izlenir. */
  runId: string;
}

export interface Ga4TotalsDto {
  sessions: number;
  engagedSessions: number;
  keyEvents: number;
  totalRevenue: number;
}

export interface Ga4ChannelTotalsDto {
  sessions: number;
  engagedSessions: number;
  keyEvents: number;
  totalRevenue: number;
  channelGroup: string;
}

export interface Ga4OverviewResponseDto {
  from: string;
  to: string;
  totals: Ga4TotalsDto;
  channels: Ga4ChannelTotalsDto[];
}

export type Ga4SortField = typeof Ga4SortField[keyof typeof Ga4SortField];


export const Ga4SortField = {
  sessions: 'sessions',
  engagedSessions: 'engagedSessions',
  keyEvents: 'keyEvents',
  totalRevenue: 'totalRevenue',
} as const;

export interface Ga4LandingPageRowDto {
  sessions: number;
  engagedSessions: number;
  keyEvents: number;
  totalRevenue: number;
  /** `md5(landingPage)`. */
  landingPageHash: string;
  landingPage: string;
}

export interface Ga4LandingPageListResponseDto {
  items: Ga4LandingPageRowDto[];
  total: number;
  page: number;
  limit: number;
}

export interface LocationReferenceDto {
  locationCode: number;
  locationName: string;
  languageCode: string;
  languageName: string;
}

export interface LocationReferenceListResponseDto {
  items: LocationReferenceDto[];
}

export type HealthCheckResultDtoStatus = typeof HealthCheckResultDtoStatus[keyof typeof HealthCheckResultDtoStatus];


export const HealthCheckResultDtoStatus = {
  up: 'up',
  down: 'down',
} as const;

export interface HealthCheckResultDto {
  status: HealthCheckResultDtoStatus;
  latencyMs?: number;
  error?: string;
}

export interface HealthChecksDto {
  database: HealthCheckResultDto;
  redis: HealthCheckResultDto;
}

export type HealthResponseDtoStatus = typeof HealthResponseDtoStatus[keyof typeof HealthResponseDtoStatus];


export const HealthResponseDtoStatus = {
  ok: 'ok',
  error: 'error',
} as const;

export interface HealthResponseDto {
  status: HealthResponseDtoStatus;
  checks: HealthChecksDto;
}

export type OrganizationsControllerListParams = {
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type MembersControllerListParams = {
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type InvitationsControllerListParams = {
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type ClientsControllerListParams = {
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * Client adında arama (ILIKE).
 * @maxLength 200
 */
search?: string;
};

export type ProjectsControllerListParams = {
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * Proje adı ya da domaininde arama (ILIKE).
 * @maxLength 200
 */
search?: string;
/**
 * Yalnız bu client'ın projelerini döner.
 */
clientId?: string;
};

export type UsageControllerReportParams = {
from?: string;
to?: string;
groupBy?: UsageGroupBy;
};

export type GscControllerOverviewParams = {
from?: string;
to?: string;
compare?: GscCompareMode;
};

export type GscControllerQueriesParams = {
from?: string;
to?: string;
sort?: GscSortField;
order?: SortOrder;
/**
 * Sorgu ya da sayfa metninde arama (ILIKE, trigram index'li).
 * @maxLength 200
 */
search?: string;
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type GscControllerPagesParams = {
from?: string;
to?: string;
sort?: GscSortField;
order?: SortOrder;
/**
 * Sorgu ya da sayfa metninde arama (ILIKE, trigram index'li).
 * @maxLength 200
 */
search?: string;
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type GscControllerQueryPagesParams = {
from?: string;
to?: string;
sort?: GscSortField;
order?: SortOrder;
/**
 * Sorgu ya da sayfa metninde arama (ILIKE, trigram index'li).
 * @maxLength 200
 */
search?: string;
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type GscControllerPageQueriesParams = {
from?: string;
to?: string;
sort?: GscSortField;
order?: SortOrder;
/**
 * Sorgu ya da sayfa metninde arama (ILIKE, trigram index'li).
 * @maxLength 200
 */
search?: string;
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

export type Ga4ControllerOverviewParams = {
from?: string;
to?: string;
};

export type Ga4ControllerLandingPagesParams = {
from?: string;
to?: string;
/**
 * `channel_group` filtresi, ör. `Organic Search`. Sorgu tarafında uygulanır (ARCHITECTURE §5.4).
 * @maxLength 50
 */
channel?: string;
sort?: Ga4SortField;
order?: SortOrder;
/**
 * Landing page metninde arama (ILIKE).
 * @maxLength 200
 */
search?: string;
/**
 * 1'den başlar.
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
};

