/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Ga4ControllerLandingPagesParams,
  Ga4ControllerOverviewParams,
  Ga4LandingPageListResponseDto,
  Ga4OverviewResponseDto,
  Ga4SyncResponseDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type ga4ControllerTriggerSyncResponse202 = {
  data: Ga4SyncResponseDto
  status: 202
}

export type ga4ControllerTriggerSyncResponse403 = {
  data: void
  status: 403
}

export type ga4ControllerTriggerSyncResponse404 = {
  data: void
  status: 404
}

export type ga4ControllerTriggerSyncResponse409 = {
  data: void
  status: 409
}

export type ga4ControllerTriggerSyncResponseSuccess = (ga4ControllerTriggerSyncResponse202) & {
  headers: Headers;
};
export type ga4ControllerTriggerSyncResponseError = (ga4ControllerTriggerSyncResponse403 | ga4ControllerTriggerSyncResponse404 | ga4ControllerTriggerSyncResponse409) & {
  headers: Headers;
};

export type ga4ControllerTriggerSyncResponse = (ga4ControllerTriggerSyncResponseSuccess | ga4ControllerTriggerSyncResponseError)

export const getGa4ControllerTriggerSyncUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/sync/ga4`
}

/**
 * @summary Son 3 günü yeniden çeker; iş kuyrukta yapılır (CLAUDE.md kural 6).
 */
export const ga4ControllerTriggerSync = async (projectId: string, options?: Parameters<typeof customFetch>[1]): Promise<ga4ControllerTriggerSyncResponse> => {

  return customFetch<ga4ControllerTriggerSyncResponse>(getGa4ControllerTriggerSyncUrl(projectId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getGa4ControllerTriggerSyncMutationKey = () => ['ga4ControllerTriggerSync'] as const;

export const getGa4ControllerTriggerSyncMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ga4ControllerTriggerSync>>, TError,Ga4ControllerTriggerSyncMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof ga4ControllerTriggerSync>>, TError,Ga4ControllerTriggerSyncMutationVariables, TContext> => {

const mutationKey = getGa4ControllerTriggerSyncMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ga4ControllerTriggerSync>>, Ga4ControllerTriggerSyncMutationVariables> = (props) => {
          const {projectId} = props ?? {};

          return  ga4ControllerTriggerSync(projectId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type Ga4ControllerTriggerSyncMutationResult = NonNullable<Awaited<ReturnType<typeof ga4ControllerTriggerSync>>>

    export type Ga4ControllerTriggerSyncMutationError = void
    export type Ga4ControllerTriggerSyncMutationVariables = {projectId: string}

    /**
 * @summary Son 3 günü yeniden çeker; iş kuyrukta yapılır (CLAUDE.md kural 6).
 */
export const useGa4ControllerTriggerSync = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ga4ControllerTriggerSync>>, TError,Ga4ControllerTriggerSyncMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ga4ControllerTriggerSync>>,
        TError,
        Ga4ControllerTriggerSyncMutationVariables,
        TContext
      > => {
      return useMutation(getGa4ControllerTriggerSyncMutationOptions(options), queryClient);
    }
    export type ga4ControllerOverviewResponse200 = {
  data: Ga4OverviewResponseDto
  status: 200
}

export type ga4ControllerOverviewResponse400 = {
  data: void
  status: 400
}

export type ga4ControllerOverviewResponse403 = {
  data: void
  status: 403
}

export type ga4ControllerOverviewResponse404 = {
  data: void
  status: 404
}

export type ga4ControllerOverviewResponseSuccess = (ga4ControllerOverviewResponse200) & {
  headers: Headers;
};
export type ga4ControllerOverviewResponseError = (ga4ControllerOverviewResponse400 | ga4ControllerOverviewResponse403 | ga4ControllerOverviewResponse404) & {
  headers: Headers;
};

export type ga4ControllerOverviewResponse = (ga4ControllerOverviewResponseSuccess | ga4ControllerOverviewResponseError)

export const getGa4ControllerOverviewUrl = (projectId: string,
    params?: Ga4ControllerOverviewParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/ga4/overview?${stringifiedParams}` : `/api/v1/projects/${projectId}/ga4/overview`
}

/**
 * @summary Kanal kırılımlı toplamlar (`ga4_daily`).
 */
export const ga4ControllerOverview = async (projectId: string,
    params?: Ga4ControllerOverviewParams, options?: Parameters<typeof customFetch>[1]): Promise<ga4ControllerOverviewResponse> => {

  return customFetch<ga4ControllerOverviewResponse>(getGa4ControllerOverviewUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGa4ControllerOverviewQueryKey = (projectId: string,
    params?: Ga4ControllerOverviewParams,) => {
    return [
    `/api/v1/projects/${projectId}/ga4/overview`, ...(params ? [params] : [])
    ] as const;
    }


export const getGa4ControllerOverviewQueryOptions = <TData = Awaited<ReturnType<typeof ga4ControllerOverview>>, TError = void>(projectId: string,
    params?: Ga4ControllerOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerOverview>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGa4ControllerOverviewQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ga4ControllerOverview>>> = ({ signal }) => ga4ControllerOverview(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerOverview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type Ga4ControllerOverviewQueryResult = NonNullable<Awaited<ReturnType<typeof ga4ControllerOverview>>>
export type Ga4ControllerOverviewQueryError = void


export function useGa4ControllerOverview<TData = Awaited<ReturnType<typeof ga4ControllerOverview>>, TError = void>(
 projectId: string,
    params: undefined |  Ga4ControllerOverviewParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerOverview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ga4ControllerOverview>>,
          TError,
          Awaited<ReturnType<typeof ga4ControllerOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGa4ControllerOverview<TData = Awaited<ReturnType<typeof ga4ControllerOverview>>, TError = void>(
 projectId: string,
    params?: Ga4ControllerOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerOverview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ga4ControllerOverview>>,
          TError,
          Awaited<ReturnType<typeof ga4ControllerOverview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGa4ControllerOverview<TData = Awaited<ReturnType<typeof ga4ControllerOverview>>, TError = void>(
 projectId: string,
    params?: Ga4ControllerOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerOverview>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Kanal kırılımlı toplamlar (`ga4_daily`).
 */

export function useGa4ControllerOverview<TData = Awaited<ReturnType<typeof ga4ControllerOverview>>, TError = void>(
 projectId: string,
    params?: Ga4ControllerOverviewParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerOverview>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGa4ControllerOverviewQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type ga4ControllerLandingPagesResponse200 = {
  data: Ga4LandingPageListResponseDto
  status: 200
}

export type ga4ControllerLandingPagesResponse400 = {
  data: void
  status: 400
}

export type ga4ControllerLandingPagesResponse403 = {
  data: void
  status: 403
}

export type ga4ControllerLandingPagesResponse404 = {
  data: void
  status: 404
}

export type ga4ControllerLandingPagesResponseSuccess = (ga4ControllerLandingPagesResponse200) & {
  headers: Headers;
};
export type ga4ControllerLandingPagesResponseError = (ga4ControllerLandingPagesResponse400 | ga4ControllerLandingPagesResponse403 | ga4ControllerLandingPagesResponse404) & {
  headers: Headers;
};

export type ga4ControllerLandingPagesResponse = (ga4ControllerLandingPagesResponseSuccess | ga4ControllerLandingPagesResponseError)

export const getGa4ControllerLandingPagesUrl = (projectId: string,
    params: Ga4ControllerLandingPagesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/ga4/landing-pages?${stringifiedParams}` : `/api/v1/projects/${projectId}/ga4/landing-pages`
}

/**
 * @summary Landing page bazında toplanmış tablo; `channel` ile filtrelenir (ör. `Organic Search`).
 */
export const ga4ControllerLandingPages = async (projectId: string,
    params: Ga4ControllerLandingPagesParams, options?: Parameters<typeof customFetch>[1]): Promise<ga4ControllerLandingPagesResponse> => {

  return customFetch<ga4ControllerLandingPagesResponse>(getGa4ControllerLandingPagesUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGa4ControllerLandingPagesQueryKey = (projectId: string,
    params?: Ga4ControllerLandingPagesParams,) => {
    return [
    `/api/v1/projects/${projectId}/ga4/landing-pages`, ...(params ? [params] : [])
    ] as const;
    }


export const getGa4ControllerLandingPagesQueryOptions = <TData = Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError = void>(projectId: string,
    params: Ga4ControllerLandingPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGa4ControllerLandingPagesQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof ga4ControllerLandingPages>>> = ({ signal }) => ga4ControllerLandingPages(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type Ga4ControllerLandingPagesQueryResult = NonNullable<Awaited<ReturnType<typeof ga4ControllerLandingPages>>>
export type Ga4ControllerLandingPagesQueryError = void


export function useGa4ControllerLandingPages<TData = Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError = void>(
 projectId: string,
    params: Ga4ControllerLandingPagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof ga4ControllerLandingPages>>,
          TError,
          Awaited<ReturnType<typeof ga4ControllerLandingPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGa4ControllerLandingPages<TData = Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError = void>(
 projectId: string,
    params: Ga4ControllerLandingPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof ga4ControllerLandingPages>>,
          TError,
          Awaited<ReturnType<typeof ga4ControllerLandingPages>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGa4ControllerLandingPages<TData = Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError = void>(
 projectId: string,
    params: Ga4ControllerLandingPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Landing page bazında toplanmış tablo; `channel` ile filtrelenir (ör. `Organic Search`).
 */

export function useGa4ControllerLandingPages<TData = Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError = void>(
 projectId: string,
    params: Ga4ControllerLandingPagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof ga4ControllerLandingPages>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGa4ControllerLandingPagesQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






