/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ConnectionListResponseDto,
  ConnectionResponseDto,
  CreateConnectionDto,
  GscSiteListResponseDto,
  ServiceAccountResponseDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type connectionsControllerListResponse200 = {
  data: ConnectionListResponseDto
  status: 200
}

export type connectionsControllerListResponse403 = {
  data: void
  status: 403
}

export type connectionsControllerListResponse404 = {
  data: void
  status: 404
}

export type connectionsControllerListResponseSuccess = (connectionsControllerListResponse200) & {
  headers: Headers;
};
export type connectionsControllerListResponseError = (connectionsControllerListResponse403 | connectionsControllerListResponse404) & {
  headers: Headers;
};

export type connectionsControllerListResponse = (connectionsControllerListResponseSuccess | connectionsControllerListResponseError)

export const getConnectionsControllerListUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/connections`
}

export const connectionsControllerList = async (projectId: string, options?: Parameters<typeof customFetch>[1]): Promise<connectionsControllerListResponse> => {

  return customFetch<connectionsControllerListResponse>(getConnectionsControllerListUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getConnectionsControllerListQueryKey = (projectId: string,) => {
    return [
    `/api/v1/projects/${projectId}/connections`
    ] as const;
    }


export const getConnectionsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof connectionsControllerList>>, TError = void>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectionsControllerListQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectionsControllerList>>> = ({ signal }) => connectionsControllerList(projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectionsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof connectionsControllerList>>>
export type ConnectionsControllerListQueryError = void


export function useConnectionsControllerList<TData = Awaited<ReturnType<typeof connectionsControllerList>>, TError = void>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionsControllerList>>,
          TError,
          Awaited<ReturnType<typeof connectionsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectionsControllerList<TData = Awaited<ReturnType<typeof connectionsControllerList>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionsControllerList>>,
          TError,
          Awaited<ReturnType<typeof connectionsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectionsControllerList<TData = Awaited<ReturnType<typeof connectionsControllerList>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useConnectionsControllerList<TData = Awaited<ReturnType<typeof connectionsControllerList>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectionsControllerListQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type connectionsControllerCreateResponse201 = {
  data: ConnectionResponseDto
  status: 201
}

export type connectionsControllerCreateResponse403 = {
  data: void
  status: 403
}

export type connectionsControllerCreateResponse404 = {
  data: void
  status: 404
}

export type connectionsControllerCreateResponse409 = {
  data: void
  status: 409
}

export type connectionsControllerCreateResponseSuccess = (connectionsControllerCreateResponse201) & {
  headers: Headers;
};
export type connectionsControllerCreateResponseError = (connectionsControllerCreateResponse403 | connectionsControllerCreateResponse404 | connectionsControllerCreateResponse409) & {
  headers: Headers;
};

export type connectionsControllerCreateResponse = (connectionsControllerCreateResponseSuccess | connectionsControllerCreateResponseError)

export const getConnectionsControllerCreateUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/connections`
}

export const connectionsControllerCreate = async (projectId: string,
    createConnectionDto: CreateConnectionDto, options?: Parameters<typeof customFetch>[1]): Promise<connectionsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<connectionsControllerCreateResponse>(getConnectionsControllerCreateUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createConnectionDto)
  }
);}





export const getConnectionsControllerCreateMutationKey = () => ['connectionsControllerCreate'] as const;

export const getConnectionsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectionsControllerCreate>>, TError,ConnectionsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof connectionsControllerCreate>>, TError,ConnectionsControllerCreateMutationVariables, TContext> => {

const mutationKey = getConnectionsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connectionsControllerCreate>>, ConnectionsControllerCreateMutationVariables> = (props) => {
          const {projectId,data} = props ?? {};

          return  connectionsControllerCreate(projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectionsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof connectionsControllerCreate>>>
    export type ConnectionsControllerCreateMutationBody = CreateConnectionDto
    export type ConnectionsControllerCreateMutationError = void
    export type ConnectionsControllerCreateMutationVariables = {projectId: string;data: CreateConnectionDto}

    export const useConnectionsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectionsControllerCreate>>, TError,ConnectionsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connectionsControllerCreate>>,
        TError,
        ConnectionsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getConnectionsControllerCreateMutationOptions(options), queryClient);
    }
    export type connectionsControllerListGscSitesResponse200 = {
  data: GscSiteListResponseDto
  status: 200
}

export type connectionsControllerListGscSitesResponse403 = {
  data: void
  status: 403
}

export type connectionsControllerListGscSitesResponse404 = {
  data: void
  status: 404
}

export type connectionsControllerListGscSitesResponseSuccess = (connectionsControllerListGscSitesResponse200) & {
  headers: Headers;
};
export type connectionsControllerListGscSitesResponseError = (connectionsControllerListGscSitesResponse403 | connectionsControllerListGscSitesResponse404) & {
  headers: Headers;
};

export type connectionsControllerListGscSitesResponse = (connectionsControllerListGscSitesResponseSuccess | connectionsControllerListGscSitesResponseError)

export const getConnectionsControllerListGscSitesUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/connections/gsc/sites`
}

/**
 * @summary Kullanıcı elle yazmak yerine service account'un erişebildiği GSC property'lerinden seçsin.
 */
export const connectionsControllerListGscSites = async (projectId: string, options?: Parameters<typeof customFetch>[1]): Promise<connectionsControllerListGscSitesResponse> => {

  return customFetch<connectionsControllerListGscSitesResponse>(getConnectionsControllerListGscSitesUrl(projectId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getConnectionsControllerListGscSitesQueryKey = (projectId: string,) => {
    return [
    `/api/v1/projects/${projectId}/connections/gsc/sites`
    ] as const;
    }


export const getConnectionsControllerListGscSitesQueryOptions = <TData = Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError = void>(projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectionsControllerListGscSitesQueryKey(projectId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectionsControllerListGscSites>>> = ({ signal }) => connectionsControllerListGscSites(projectId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectionsControllerListGscSitesQueryResult = NonNullable<Awaited<ReturnType<typeof connectionsControllerListGscSites>>>
export type ConnectionsControllerListGscSitesQueryError = void


export function useConnectionsControllerListGscSites<TData = Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError = void>(
 projectId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionsControllerListGscSites>>,
          TError,
          Awaited<ReturnType<typeof connectionsControllerListGscSites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectionsControllerListGscSites<TData = Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionsControllerListGscSites>>,
          TError,
          Awaited<ReturnType<typeof connectionsControllerListGscSites>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectionsControllerListGscSites<TData = Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Kullanıcı elle yazmak yerine service account'un erişebildiği GSC property'lerinden seçsin.
 */

export function useConnectionsControllerListGscSites<TData = Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError = void>(
 projectId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionsControllerListGscSites>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectionsControllerListGscSitesQueryOptions(projectId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type connectionControllerGetServiceAccountResponse200 = {
  data: ServiceAccountResponseDto
  status: 200
}

export type connectionControllerGetServiceAccountResponse403 = {
  data: void
  status: 403
}

export type connectionControllerGetServiceAccountResponseSuccess = (connectionControllerGetServiceAccountResponse200) & {
  headers: Headers;
};
export type connectionControllerGetServiceAccountResponseError = (connectionControllerGetServiceAccountResponse403) & {
  headers: Headers;
};

export type connectionControllerGetServiceAccountResponse = (connectionControllerGetServiceAccountResponseSuccess | connectionControllerGetServiceAccountResponseError)

export const getConnectionControllerGetServiceAccountUrl = () => {




  return `/api/v1/connections/service-account`
}

/**
 * @summary Kullanıcının property'ye ekleyeceği sistem service account e-postası.
 */
export const connectionControllerGetServiceAccount = async ( options?: Parameters<typeof customFetch>[1]): Promise<connectionControllerGetServiceAccountResponse> => {

  return customFetch<connectionControllerGetServiceAccountResponse>(getConnectionControllerGetServiceAccountUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getConnectionControllerGetServiceAccountQueryKey = () => {
    return [
    `/api/v1/connections/service-account`
    ] as const;
    }


export const getConnectionControllerGetServiceAccountQueryOptions = <TData = Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectionControllerGetServiceAccountQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>> = ({ signal }) => connectionControllerGetServiceAccount({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectionControllerGetServiceAccountQueryResult = NonNullable<Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>>
export type ConnectionControllerGetServiceAccountQueryError = void


export function useConnectionControllerGetServiceAccount<TData = Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>,
          TError,
          Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectionControllerGetServiceAccount<TData = Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>,
          TError,
          Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectionControllerGetServiceAccount<TData = Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Kullanıcının property'ye ekleyeceği sistem service account e-postası.
 */

export function useConnectionControllerGetServiceAccount<TData = Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerGetServiceAccount>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectionControllerGetServiceAccountQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type connectionControllerFindOneResponse200 = {
  data: ConnectionResponseDto
  status: 200
}

export type connectionControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type connectionControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type connectionControllerFindOneResponseSuccess = (connectionControllerFindOneResponse200) & {
  headers: Headers;
};
export type connectionControllerFindOneResponseError = (connectionControllerFindOneResponse403 | connectionControllerFindOneResponse404) & {
  headers: Headers;
};

export type connectionControllerFindOneResponse = (connectionControllerFindOneResponseSuccess | connectionControllerFindOneResponseError)

export const getConnectionControllerFindOneUrl = (connectionId: string,) => {




  return `/api/v1/connections/${connectionId}`
}

export const connectionControllerFindOne = async (connectionId: string, options?: Parameters<typeof customFetch>[1]): Promise<connectionControllerFindOneResponse> => {

  return customFetch<connectionControllerFindOneResponse>(getConnectionControllerFindOneUrl(connectionId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getConnectionControllerFindOneQueryKey = (connectionId: string,) => {
    return [
    `/api/v1/connections/${connectionId}`
    ] as const;
    }


export const getConnectionControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof connectionControllerFindOne>>, TError = void>(connectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getConnectionControllerFindOneQueryKey(connectionId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof connectionControllerFindOne>>> = ({ signal }) => connectionControllerFindOne(connectionId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: connectionId !== null && connectionId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof connectionControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ConnectionControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof connectionControllerFindOne>>>
export type ConnectionControllerFindOneQueryError = void


export function useConnectionControllerFindOne<TData = Awaited<ReturnType<typeof connectionControllerFindOne>>, TError = void>(
 connectionId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof connectionControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectionControllerFindOne<TData = Awaited<ReturnType<typeof connectionControllerFindOne>>, TError = void>(
 connectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof connectionControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useConnectionControllerFindOne<TData = Awaited<ReturnType<typeof connectionControllerFindOne>>, TError = void>(
 connectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useConnectionControllerFindOne<TData = Awaited<ReturnType<typeof connectionControllerFindOne>>, TError = void>(
 connectionId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof connectionControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getConnectionControllerFindOneQueryOptions(connectionId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type connectionControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type connectionControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type connectionControllerDeleteResponse404 = {
  data: void
  status: 404
}

export type connectionControllerDeleteResponseSuccess = (connectionControllerDeleteResponse204) & {
  headers: Headers;
};
export type connectionControllerDeleteResponseError = (connectionControllerDeleteResponse403 | connectionControllerDeleteResponse404) & {
  headers: Headers;
};

export type connectionControllerDeleteResponse = (connectionControllerDeleteResponseSuccess | connectionControllerDeleteResponseError)

export const getConnectionControllerDeleteUrl = (connectionId: string,) => {




  return `/api/v1/connections/${connectionId}`
}

export const connectionControllerDelete = async (connectionId: string, options?: Parameters<typeof customFetch>[1]): Promise<connectionControllerDeleteResponse> => {

  return customFetch<connectionControllerDeleteResponse>(getConnectionControllerDeleteUrl(connectionId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getConnectionControllerDeleteMutationKey = () => ['connectionControllerDelete'] as const;

export const getConnectionControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectionControllerDelete>>, TError,ConnectionControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof connectionControllerDelete>>, TError,ConnectionControllerDeleteMutationVariables, TContext> => {

const mutationKey = getConnectionControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connectionControllerDelete>>, ConnectionControllerDeleteMutationVariables> = (props) => {
          const {connectionId} = props ?? {};

          return  connectionControllerDelete(connectionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectionControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof connectionControllerDelete>>>

    export type ConnectionControllerDeleteMutationError = void
    export type ConnectionControllerDeleteMutationVariables = {connectionId: string}

    export const useConnectionControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectionControllerDelete>>, TError,ConnectionControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connectionControllerDelete>>,
        TError,
        ConnectionControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getConnectionControllerDeleteMutationOptions(options), queryClient);
    }
    export type connectionControllerVerifyResponse200 = {
  data: ConnectionResponseDto
  status: 200
}

export type connectionControllerVerifyResponse403 = {
  data: void
  status: 403
}

export type connectionControllerVerifyResponse404 = {
  data: void
  status: 404
}

export type connectionControllerVerifyResponseSuccess = (connectionControllerVerifyResponse200) & {
  headers: Headers;
};
export type connectionControllerVerifyResponseError = (connectionControllerVerifyResponse403 | connectionControllerVerifyResponse404) & {
  headers: Headers;
};

export type connectionControllerVerifyResponse = (connectionControllerVerifyResponseSuccess | connectionControllerVerifyResponseError)

export const getConnectionControllerVerifyUrl = (connectionId: string,) => {




  return `/api/v1/connections/${connectionId}/verify`
}

export const connectionControllerVerify = async (connectionId: string, options?: Parameters<typeof customFetch>[1]): Promise<connectionControllerVerifyResponse> => {

  return customFetch<connectionControllerVerifyResponse>(getConnectionControllerVerifyUrl(connectionId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getConnectionControllerVerifyMutationKey = () => ['connectionControllerVerify'] as const;

export const getConnectionControllerVerifyMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectionControllerVerify>>, TError,ConnectionControllerVerifyMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof connectionControllerVerify>>, TError,ConnectionControllerVerifyMutationVariables, TContext> => {

const mutationKey = getConnectionControllerVerifyMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof connectionControllerVerify>>, ConnectionControllerVerifyMutationVariables> = (props) => {
          const {connectionId} = props ?? {};

          return  connectionControllerVerify(connectionId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ConnectionControllerVerifyMutationResult = NonNullable<Awaited<ReturnType<typeof connectionControllerVerify>>>

    export type ConnectionControllerVerifyMutationError = void
    export type ConnectionControllerVerifyMutationVariables = {connectionId: string}

    export const useConnectionControllerVerify = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof connectionControllerVerify>>, TError,ConnectionControllerVerifyMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof connectionControllerVerify>>,
        TError,
        ConnectionControllerVerifyMutationVariables,
        TContext
      > => {
      return useMutation(getConnectionControllerVerifyMutationOptions(options), queryClient);
    }
