/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Seo Platform API
 * Çok kiracılı SEO takip ve otomasyon platformu API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AlertEventListResponseDto,
  AlertEventsControllerListParams,
  AlertRuleListResponseDto,
  AlertRuleResponseDto,
  AlertRulesControllerListParams,
  CreateAlertRuleDto,
  CreateNotificationChannelDto,
  NotificationChannelListResponseDto,
  NotificationChannelResponseDto,
  UpdateAlertRuleDto,
  UpdateNotificationChannelDto
} from '../endpoints.schemas';

import { customFetch } from '../../lib/http/custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type alertRulesControllerListResponse200 = {
  data: AlertRuleListResponseDto
  status: 200
}

export type alertRulesControllerListResponse403 = {
  data: void
  status: 403
}

export type alertRulesControllerListResponse404 = {
  data: void
  status: 404
}

export type alertRulesControllerListResponseSuccess = (alertRulesControllerListResponse200) & {
  headers: Headers;
};
export type alertRulesControllerListResponseError = (alertRulesControllerListResponse403 | alertRulesControllerListResponse404) & {
  headers: Headers;
};

export type alertRulesControllerListResponse = (alertRulesControllerListResponseSuccess | alertRulesControllerListResponseError)

export const getAlertRulesControllerListUrl = (projectId: string,
    params: AlertRulesControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/alert-rules?${stringifiedParams}` : `/api/v1/projects/${projectId}/alert-rules`
}

export const alertRulesControllerList = async (projectId: string,
    params: AlertRulesControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<alertRulesControllerListResponse> => {

  return customFetch<alertRulesControllerListResponse>(getAlertRulesControllerListUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAlertRulesControllerListQueryKey = (projectId: string,
    params?: AlertRulesControllerListParams,) => {
    return [
    `/api/v1/projects/${projectId}/alert-rules`, ...(params ? [params] : [])
    ] as const;
    }


export const getAlertRulesControllerListQueryOptions = <TData = Awaited<ReturnType<typeof alertRulesControllerList>>, TError = void>(projectId: string,
    params: AlertRulesControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAlertRulesControllerListQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof alertRulesControllerList>>> = ({ signal }) => alertRulesControllerList(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AlertRulesControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof alertRulesControllerList>>>
export type AlertRulesControllerListQueryError = void


export function useAlertRulesControllerList<TData = Awaited<ReturnType<typeof alertRulesControllerList>>, TError = void>(
 projectId: string,
    params: AlertRulesControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof alertRulesControllerList>>,
          TError,
          Awaited<ReturnType<typeof alertRulesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlertRulesControllerList<TData = Awaited<ReturnType<typeof alertRulesControllerList>>, TError = void>(
 projectId: string,
    params: AlertRulesControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof alertRulesControllerList>>,
          TError,
          Awaited<ReturnType<typeof alertRulesControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlertRulesControllerList<TData = Awaited<ReturnType<typeof alertRulesControllerList>>, TError = void>(
 projectId: string,
    params: AlertRulesControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAlertRulesControllerList<TData = Awaited<ReturnType<typeof alertRulesControllerList>>, TError = void>(
 projectId: string,
    params: AlertRulesControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAlertRulesControllerListQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type alertRulesControllerCreateResponse201 = {
  data: AlertRuleResponseDto
  status: 201
}

export type alertRulesControllerCreateResponse403 = {
  data: void
  status: 403
}

export type alertRulesControllerCreateResponse404 = {
  data: void
  status: 404
}

export type alertRulesControllerCreateResponseSuccess = (alertRulesControllerCreateResponse201) & {
  headers: Headers;
};
export type alertRulesControllerCreateResponseError = (alertRulesControllerCreateResponse403 | alertRulesControllerCreateResponse404) & {
  headers: Headers;
};

export type alertRulesControllerCreateResponse = (alertRulesControllerCreateResponseSuccess | alertRulesControllerCreateResponseError)

export const getAlertRulesControllerCreateUrl = (projectId: string,) => {




  return `/api/v1/projects/${projectId}/alert-rules`
}

export const alertRulesControllerCreate = async (projectId: string,
    createAlertRuleDto: CreateAlertRuleDto, options?: Parameters<typeof customFetch>[1]): Promise<alertRulesControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<alertRulesControllerCreateResponse>(getAlertRulesControllerCreateUrl(projectId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createAlertRuleDto)
  }
);}





export const getAlertRulesControllerCreateMutationKey = () => ['alertRulesControllerCreate'] as const;

export const getAlertRulesControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerCreate>>, TError,AlertRulesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerCreate>>, TError,AlertRulesControllerCreateMutationVariables, TContext> => {

const mutationKey = getAlertRulesControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof alertRulesControllerCreate>>, AlertRulesControllerCreateMutationVariables> = (props) => {
          const {projectId,data} = props ?? {};

          return  alertRulesControllerCreate(projectId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AlertRulesControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof alertRulesControllerCreate>>>
    export type AlertRulesControllerCreateMutationBody = CreateAlertRuleDto
    export type AlertRulesControllerCreateMutationError = void
    export type AlertRulesControllerCreateMutationVariables = {projectId: string;data: CreateAlertRuleDto}

    export const useAlertRulesControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerCreate>>, TError,AlertRulesControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof alertRulesControllerCreate>>,
        TError,
        AlertRulesControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getAlertRulesControllerCreateMutationOptions(options), queryClient);
    }
    export type alertRulesControllerFindOneResponse200 = {
  data: AlertRuleResponseDto
  status: 200
}

export type alertRulesControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type alertRulesControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type alertRulesControllerFindOneResponseSuccess = (alertRulesControllerFindOneResponse200) & {
  headers: Headers;
};
export type alertRulesControllerFindOneResponseError = (alertRulesControllerFindOneResponse403 | alertRulesControllerFindOneResponse404) & {
  headers: Headers;
};

export type alertRulesControllerFindOneResponse = (alertRulesControllerFindOneResponseSuccess | alertRulesControllerFindOneResponseError)

export const getAlertRulesControllerFindOneUrl = (projectId: string,
    ruleId: string,) => {




  return `/api/v1/projects/${projectId}/alert-rules/${ruleId}`
}

export const alertRulesControllerFindOne = async (projectId: string,
    ruleId: string, options?: Parameters<typeof customFetch>[1]): Promise<alertRulesControllerFindOneResponse> => {

  return customFetch<alertRulesControllerFindOneResponse>(getAlertRulesControllerFindOneUrl(projectId,ruleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAlertRulesControllerFindOneQueryKey = (projectId: string,
    ruleId: string,) => {
    return [
    `/api/v1/projects/${projectId}/alert-rules/${ruleId}`
    ] as const;
    }


export const getAlertRulesControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError = void>(projectId: string,
    ruleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAlertRulesControllerFindOneQueryKey(projectId,ruleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof alertRulesControllerFindOne>>> = ({ signal }) => alertRulesControllerFindOne(projectId,ruleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined && ruleId !== null && ruleId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AlertRulesControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof alertRulesControllerFindOne>>>
export type AlertRulesControllerFindOneQueryError = void


export function useAlertRulesControllerFindOne<TData = Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError = void>(
 projectId: string,
    ruleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof alertRulesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof alertRulesControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlertRulesControllerFindOne<TData = Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError = void>(
 projectId: string,
    ruleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof alertRulesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof alertRulesControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlertRulesControllerFindOne<TData = Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError = void>(
 projectId: string,
    ruleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAlertRulesControllerFindOne<TData = Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError = void>(
 projectId: string,
    ruleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertRulesControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAlertRulesControllerFindOneQueryOptions(projectId,ruleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type alertRulesControllerUpdateResponse200 = {
  data: AlertRuleResponseDto
  status: 200
}

export type alertRulesControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type alertRulesControllerUpdateResponse404 = {
  data: void
  status: 404
}

export type alertRulesControllerUpdateResponseSuccess = (alertRulesControllerUpdateResponse200) & {
  headers: Headers;
};
export type alertRulesControllerUpdateResponseError = (alertRulesControllerUpdateResponse403 | alertRulesControllerUpdateResponse404) & {
  headers: Headers;
};

export type alertRulesControllerUpdateResponse = (alertRulesControllerUpdateResponseSuccess | alertRulesControllerUpdateResponseError)

export const getAlertRulesControllerUpdateUrl = (projectId: string,
    ruleId: string,) => {




  return `/api/v1/projects/${projectId}/alert-rules/${ruleId}`
}

export const alertRulesControllerUpdate = async (projectId: string,
    ruleId: string,
    updateAlertRuleDto: UpdateAlertRuleDto, options?: Parameters<typeof customFetch>[1]): Promise<alertRulesControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<alertRulesControllerUpdateResponse>(getAlertRulesControllerUpdateUrl(projectId,ruleId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateAlertRuleDto)
  }
);}





export const getAlertRulesControllerUpdateMutationKey = () => ['alertRulesControllerUpdate'] as const;

export const getAlertRulesControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerUpdate>>, TError,AlertRulesControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerUpdate>>, TError,AlertRulesControllerUpdateMutationVariables, TContext> => {

const mutationKey = getAlertRulesControllerUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof alertRulesControllerUpdate>>, AlertRulesControllerUpdateMutationVariables> = (props) => {
          const {projectId,ruleId,data} = props ?? {};

          return  alertRulesControllerUpdate(projectId,ruleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AlertRulesControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof alertRulesControllerUpdate>>>
    export type AlertRulesControllerUpdateMutationBody = UpdateAlertRuleDto
    export type AlertRulesControllerUpdateMutationError = void
    export type AlertRulesControllerUpdateMutationVariables = {projectId: string;ruleId: string;data: UpdateAlertRuleDto}

    export const useAlertRulesControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerUpdate>>, TError,AlertRulesControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof alertRulesControllerUpdate>>,
        TError,
        AlertRulesControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getAlertRulesControllerUpdateMutationOptions(options), queryClient);
    }
    export type alertRulesControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type alertRulesControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type alertRulesControllerDeleteResponse404 = {
  data: void
  status: 404
}

export type alertRulesControllerDeleteResponseSuccess = (alertRulesControllerDeleteResponse204) & {
  headers: Headers;
};
export type alertRulesControllerDeleteResponseError = (alertRulesControllerDeleteResponse403 | alertRulesControllerDeleteResponse404) & {
  headers: Headers;
};

export type alertRulesControllerDeleteResponse = (alertRulesControllerDeleteResponseSuccess | alertRulesControllerDeleteResponseError)

export const getAlertRulesControllerDeleteUrl = (projectId: string,
    ruleId: string,) => {




  return `/api/v1/projects/${projectId}/alert-rules/${ruleId}`
}

export const alertRulesControllerDelete = async (projectId: string,
    ruleId: string, options?: Parameters<typeof customFetch>[1]): Promise<alertRulesControllerDeleteResponse> => {

  return customFetch<alertRulesControllerDeleteResponse>(getAlertRulesControllerDeleteUrl(projectId,ruleId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getAlertRulesControllerDeleteMutationKey = () => ['alertRulesControllerDelete'] as const;

export const getAlertRulesControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerDelete>>, TError,AlertRulesControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerDelete>>, TError,AlertRulesControllerDeleteMutationVariables, TContext> => {

const mutationKey = getAlertRulesControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof alertRulesControllerDelete>>, AlertRulesControllerDeleteMutationVariables> = (props) => {
          const {projectId,ruleId} = props ?? {};

          return  alertRulesControllerDelete(projectId,ruleId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AlertRulesControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof alertRulesControllerDelete>>>

    export type AlertRulesControllerDeleteMutationError = void
    export type AlertRulesControllerDeleteMutationVariables = {projectId: string;ruleId: string}

    export const useAlertRulesControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof alertRulesControllerDelete>>, TError,AlertRulesControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof alertRulesControllerDelete>>,
        TError,
        AlertRulesControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getAlertRulesControllerDeleteMutationOptions(options), queryClient);
    }
    export type alertEventsControllerListResponse200 = {
  data: AlertEventListResponseDto
  status: 200
}

export type alertEventsControllerListResponse403 = {
  data: void
  status: 403
}

export type alertEventsControllerListResponse404 = {
  data: void
  status: 404
}

export type alertEventsControllerListResponseSuccess = (alertEventsControllerListResponse200) & {
  headers: Headers;
};
export type alertEventsControllerListResponseError = (alertEventsControllerListResponse403 | alertEventsControllerListResponse404) & {
  headers: Headers;
};

export type alertEventsControllerListResponse = (alertEventsControllerListResponseSuccess | alertEventsControllerListResponseError)

export const getAlertEventsControllerListUrl = (projectId: string,
    params: AlertEventsControllerListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/projects/${projectId}/alert-events?${stringifiedParams}` : `/api/v1/projects/${projectId}/alert-events`
}

export const alertEventsControllerList = async (projectId: string,
    params: AlertEventsControllerListParams, options?: Parameters<typeof customFetch>[1]): Promise<alertEventsControllerListResponse> => {

  return customFetch<alertEventsControllerListResponse>(getAlertEventsControllerListUrl(projectId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAlertEventsControllerListQueryKey = (projectId: string,
    params?: AlertEventsControllerListParams,) => {
    return [
    `/api/v1/projects/${projectId}/alert-events`, ...(params ? [params] : [])
    ] as const;
    }


export const getAlertEventsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof alertEventsControllerList>>, TError = void>(projectId: string,
    params: AlertEventsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertEventsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAlertEventsControllerListQueryKey(projectId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof alertEventsControllerList>>> = ({ signal }) => alertEventsControllerList(projectId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: projectId !== null && projectId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof alertEventsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AlertEventsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof alertEventsControllerList>>>
export type AlertEventsControllerListQueryError = void


export function useAlertEventsControllerList<TData = Awaited<ReturnType<typeof alertEventsControllerList>>, TError = void>(
 projectId: string,
    params: AlertEventsControllerListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertEventsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof alertEventsControllerList>>,
          TError,
          Awaited<ReturnType<typeof alertEventsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlertEventsControllerList<TData = Awaited<ReturnType<typeof alertEventsControllerList>>, TError = void>(
 projectId: string,
    params: AlertEventsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertEventsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof alertEventsControllerList>>,
          TError,
          Awaited<ReturnType<typeof alertEventsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAlertEventsControllerList<TData = Awaited<ReturnType<typeof alertEventsControllerList>>, TError = void>(
 projectId: string,
    params: AlertEventsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertEventsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAlertEventsControllerList<TData = Awaited<ReturnType<typeof alertEventsControllerList>>, TError = void>(
 projectId: string,
    params: AlertEventsControllerListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof alertEventsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAlertEventsControllerListQueryOptions(projectId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type notificationChannelsControllerListResponse200 = {
  data: NotificationChannelListResponseDto
  status: 200
}

export type notificationChannelsControllerListResponse403 = {
  data: void
  status: 403
}

export type notificationChannelsControllerListResponseSuccess = (notificationChannelsControllerListResponse200) & {
  headers: Headers;
};
export type notificationChannelsControllerListResponseError = (notificationChannelsControllerListResponse403) & {
  headers: Headers;
};

export type notificationChannelsControllerListResponse = (notificationChannelsControllerListResponseSuccess | notificationChannelsControllerListResponseError)

export const getNotificationChannelsControllerListUrl = () => {




  return `/api/v1/notification-channels`
}

export const notificationChannelsControllerList = async ( options?: Parameters<typeof customFetch>[1]): Promise<notificationChannelsControllerListResponse> => {

  return customFetch<notificationChannelsControllerListResponse>(getNotificationChannelsControllerListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getNotificationChannelsControllerListQueryKey = () => {
    return [
    `/api/v1/notification-channels`
    ] as const;
    }


export const getNotificationChannelsControllerListQueryOptions = <TData = Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationChannelsControllerListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationChannelsControllerList>>> = ({ signal }) => notificationChannelsControllerList({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationChannelsControllerListQueryResult = NonNullable<Awaited<ReturnType<typeof notificationChannelsControllerList>>>
export type NotificationChannelsControllerListQueryError = void


export function useNotificationChannelsControllerList<TData = Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationChannelsControllerList>>,
          TError,
          Awaited<ReturnType<typeof notificationChannelsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationChannelsControllerList<TData = Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationChannelsControllerList>>,
          TError,
          Awaited<ReturnType<typeof notificationChannelsControllerList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationChannelsControllerList<TData = Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationChannelsControllerList<TData = Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerList>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationChannelsControllerListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type notificationChannelsControllerCreateResponse201 = {
  data: NotificationChannelResponseDto
  status: 201
}

export type notificationChannelsControllerCreateResponse403 = {
  data: void
  status: 403
}

export type notificationChannelsControllerCreateResponseSuccess = (notificationChannelsControllerCreateResponse201) & {
  headers: Headers;
};
export type notificationChannelsControllerCreateResponseError = (notificationChannelsControllerCreateResponse403) & {
  headers: Headers;
};

export type notificationChannelsControllerCreateResponse = (notificationChannelsControllerCreateResponseSuccess | notificationChannelsControllerCreateResponseError)

export const getNotificationChannelsControllerCreateUrl = () => {




  return `/api/v1/notification-channels`
}

export const notificationChannelsControllerCreate = async (createNotificationChannelDto: CreateNotificationChannelDto, options?: Parameters<typeof customFetch>[1]): Promise<notificationChannelsControllerCreateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<notificationChannelsControllerCreateResponse>(getNotificationChannelsControllerCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createNotificationChannelDto)
  }
);}





export const getNotificationChannelsControllerCreateMutationKey = () => ['notificationChannelsControllerCreate'] as const;

export const getNotificationChannelsControllerCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerCreate>>, TError,NotificationChannelsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerCreate>>, TError,NotificationChannelsControllerCreateMutationVariables, TContext> => {

const mutationKey = getNotificationChannelsControllerCreateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationChannelsControllerCreate>>, NotificationChannelsControllerCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  notificationChannelsControllerCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationChannelsControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof notificationChannelsControllerCreate>>>
    export type NotificationChannelsControllerCreateMutationBody = CreateNotificationChannelDto
    export type NotificationChannelsControllerCreateMutationError = void
    export type NotificationChannelsControllerCreateMutationVariables = {data: CreateNotificationChannelDto}

    export const useNotificationChannelsControllerCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerCreate>>, TError,NotificationChannelsControllerCreateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notificationChannelsControllerCreate>>,
        TError,
        NotificationChannelsControllerCreateMutationVariables,
        TContext
      > => {
      return useMutation(getNotificationChannelsControllerCreateMutationOptions(options), queryClient);
    }
    export type notificationChannelsControllerFindOneResponse200 = {
  data: NotificationChannelResponseDto
  status: 200
}

export type notificationChannelsControllerFindOneResponse403 = {
  data: void
  status: 403
}

export type notificationChannelsControllerFindOneResponse404 = {
  data: void
  status: 404
}

export type notificationChannelsControllerFindOneResponseSuccess = (notificationChannelsControllerFindOneResponse200) & {
  headers: Headers;
};
export type notificationChannelsControllerFindOneResponseError = (notificationChannelsControllerFindOneResponse403 | notificationChannelsControllerFindOneResponse404) & {
  headers: Headers;
};

export type notificationChannelsControllerFindOneResponse = (notificationChannelsControllerFindOneResponseSuccess | notificationChannelsControllerFindOneResponseError)

export const getNotificationChannelsControllerFindOneUrl = (channelId: string,) => {




  return `/api/v1/notification-channels/${channelId}`
}

export const notificationChannelsControllerFindOne = async (channelId: string, options?: Parameters<typeof customFetch>[1]): Promise<notificationChannelsControllerFindOneResponse> => {

  return customFetch<notificationChannelsControllerFindOneResponse>(getNotificationChannelsControllerFindOneUrl(channelId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getNotificationChannelsControllerFindOneQueryKey = (channelId: string,) => {
    return [
    `/api/v1/notification-channels/${channelId}`
    ] as const;
    }


export const getNotificationChannelsControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError = void>(channelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getNotificationChannelsControllerFindOneQueryKey(channelId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>> = ({ signal }) => notificationChannelsControllerFindOne(channelId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: channelId !== null && channelId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type NotificationChannelsControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>>
export type NotificationChannelsControllerFindOneQueryError = void


export function useNotificationChannelsControllerFindOne<TData = Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError = void>(
 channelId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationChannelsControllerFindOne<TData = Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError = void>(
 channelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useNotificationChannelsControllerFindOne<TData = Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError = void>(
 channelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useNotificationChannelsControllerFindOne<TData = Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError = void>(
 channelId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof notificationChannelsControllerFindOne>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getNotificationChannelsControllerFindOneQueryOptions(channelId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type notificationChannelsControllerUpdateResponse200 = {
  data: NotificationChannelResponseDto
  status: 200
}

export type notificationChannelsControllerUpdateResponse403 = {
  data: void
  status: 403
}

export type notificationChannelsControllerUpdateResponse404 = {
  data: void
  status: 404
}

export type notificationChannelsControllerUpdateResponseSuccess = (notificationChannelsControllerUpdateResponse200) & {
  headers: Headers;
};
export type notificationChannelsControllerUpdateResponseError = (notificationChannelsControllerUpdateResponse403 | notificationChannelsControllerUpdateResponse404) & {
  headers: Headers;
};

export type notificationChannelsControllerUpdateResponse = (notificationChannelsControllerUpdateResponseSuccess | notificationChannelsControllerUpdateResponseError)

export const getNotificationChannelsControllerUpdateUrl = (channelId: string,) => {




  return `/api/v1/notification-channels/${channelId}`
}

export const notificationChannelsControllerUpdate = async (channelId: string,
    updateNotificationChannelDto: UpdateNotificationChannelDto, options?: Parameters<typeof customFetch>[1]): Promise<notificationChannelsControllerUpdateResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return customFetch<notificationChannelsControllerUpdateResponse>(getNotificationChannelsControllerUpdateUrl(channelId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateNotificationChannelDto)
  }
);}





export const getNotificationChannelsControllerUpdateMutationKey = () => ['notificationChannelsControllerUpdate'] as const;

export const getNotificationChannelsControllerUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerUpdate>>, TError,NotificationChannelsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerUpdate>>, TError,NotificationChannelsControllerUpdateMutationVariables, TContext> => {

const mutationKey = getNotificationChannelsControllerUpdateMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationChannelsControllerUpdate>>, NotificationChannelsControllerUpdateMutationVariables> = (props) => {
          const {channelId,data} = props ?? {};

          return  notificationChannelsControllerUpdate(channelId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationChannelsControllerUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof notificationChannelsControllerUpdate>>>
    export type NotificationChannelsControllerUpdateMutationBody = UpdateNotificationChannelDto
    export type NotificationChannelsControllerUpdateMutationError = void
    export type NotificationChannelsControllerUpdateMutationVariables = {channelId: string;data: UpdateNotificationChannelDto}

    export const useNotificationChannelsControllerUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerUpdate>>, TError,NotificationChannelsControllerUpdateMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notificationChannelsControllerUpdate>>,
        TError,
        NotificationChannelsControllerUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getNotificationChannelsControllerUpdateMutationOptions(options), queryClient);
    }
    export type notificationChannelsControllerDeleteResponse204 = {
  data: void
  status: 204
}

export type notificationChannelsControllerDeleteResponse403 = {
  data: void
  status: 403
}

export type notificationChannelsControllerDeleteResponse404 = {
  data: void
  status: 404
}

export type notificationChannelsControllerDeleteResponseSuccess = (notificationChannelsControllerDeleteResponse204) & {
  headers: Headers;
};
export type notificationChannelsControllerDeleteResponseError = (notificationChannelsControllerDeleteResponse403 | notificationChannelsControllerDeleteResponse404) & {
  headers: Headers;
};

export type notificationChannelsControllerDeleteResponse = (notificationChannelsControllerDeleteResponseSuccess | notificationChannelsControllerDeleteResponseError)

export const getNotificationChannelsControllerDeleteUrl = (channelId: string,) => {




  return `/api/v1/notification-channels/${channelId}`
}

export const notificationChannelsControllerDelete = async (channelId: string, options?: Parameters<typeof customFetch>[1]): Promise<notificationChannelsControllerDeleteResponse> => {

  return customFetch<notificationChannelsControllerDeleteResponse>(getNotificationChannelsControllerDeleteUrl(channelId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getNotificationChannelsControllerDeleteMutationKey = () => ['notificationChannelsControllerDelete'] as const;

export const getNotificationChannelsControllerDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerDelete>>, TError,NotificationChannelsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerDelete>>, TError,NotificationChannelsControllerDeleteMutationVariables, TContext> => {

const mutationKey = getNotificationChannelsControllerDeleteMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationChannelsControllerDelete>>, NotificationChannelsControllerDeleteMutationVariables> = (props) => {
          const {channelId} = props ?? {};

          return  notificationChannelsControllerDelete(channelId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationChannelsControllerDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof notificationChannelsControllerDelete>>>

    export type NotificationChannelsControllerDeleteMutationError = void
    export type NotificationChannelsControllerDeleteMutationVariables = {channelId: string}

    export const useNotificationChannelsControllerDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerDelete>>, TError,NotificationChannelsControllerDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notificationChannelsControllerDelete>>,
        TError,
        NotificationChannelsControllerDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getNotificationChannelsControllerDeleteMutationOptions(options), queryClient);
    }
    export type notificationChannelsControllerTestResponse204 = {
  data: void
  status: 204
}

export type notificationChannelsControllerTestResponse403 = {
  data: void
  status: 403
}

export type notificationChannelsControllerTestResponse404 = {
  data: void
  status: 404
}

export type notificationChannelsControllerTestResponseSuccess = (notificationChannelsControllerTestResponse204) & {
  headers: Headers;
};
export type notificationChannelsControllerTestResponseError = (notificationChannelsControllerTestResponse403 | notificationChannelsControllerTestResponse404) & {
  headers: Headers;
};

export type notificationChannelsControllerTestResponse = (notificationChannelsControllerTestResponseSuccess | notificationChannelsControllerTestResponseError)

export const getNotificationChannelsControllerTestUrl = (channelId: string,) => {




  return `/api/v1/notification-channels/${channelId}/test`
}

export const notificationChannelsControllerTest = async (channelId: string, options?: Parameters<typeof customFetch>[1]): Promise<notificationChannelsControllerTestResponse> => {

  return customFetch<notificationChannelsControllerTestResponse>(getNotificationChannelsControllerTestUrl(channelId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getNotificationChannelsControllerTestMutationKey = () => ['notificationChannelsControllerTest'] as const;

export const getNotificationChannelsControllerTestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerTest>>, TError,NotificationChannelsControllerTestMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerTest>>, TError,NotificationChannelsControllerTestMutationVariables, TContext> => {

const mutationKey = getNotificationChannelsControllerTestMutationKey();
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof notificationChannelsControllerTest>>, NotificationChannelsControllerTestMutationVariables> = (props) => {
          const {channelId} = props ?? {};

          return  notificationChannelsControllerTest(channelId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type NotificationChannelsControllerTestMutationResult = NonNullable<Awaited<ReturnType<typeof notificationChannelsControllerTest>>>

    export type NotificationChannelsControllerTestMutationError = void
    export type NotificationChannelsControllerTestMutationVariables = {channelId: string}

    export const useNotificationChannelsControllerTest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof notificationChannelsControllerTest>>, TError,NotificationChannelsControllerTestMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof notificationChannelsControllerTest>>,
        TError,
        NotificationChannelsControllerTestMutationVariables,
        TContext
      > => {
      return useMutation(getNotificationChannelsControllerTestMutationOptions(options), queryClient);
    }
